react-native-elements/react-native-elements

.babelrc
Readme.MD
package.json
src/config/fonts.js

- Removes hard dependency on react-native-vector-icons and instead makes it a peerDependency, so we can substitute our own implementation that works with Exponent.
- Ship uncompiled code for now as it's quite a small project and makes it easier to debug issues by editing it inside of your node_modules (we went back from shipping compiled code for ex-navigation as well because it was a hassle for users)
- Switch from Lato to HelveticaNeue on iOS by default.
Let me know if you're OK with these changes or if there are other approaches you'd prefer. Looking like a really great project so far, thanks @dabit3!

Make the project compatible with Exponent

---

Readme.MD

It didn't sound really obvious to me that in order to use "Icon Buttons" as stated in the title of the section we have to put "reverse" as a props to the Icon component.
In fact, I had to try all samples to understand that, so it might be the case for others too.

Hint for reverse trick: make icons look like button

---

src/buttons/Button.js
src/social/SocialIcon.js

**Issue** #56 
Accepts the following new props. 
-   **loading**: PropTypes.bool
-   **activityIndicatorStyle**: PropTypes.any
-   **loadingLeft**: PropTypes.bool
By default the activityIndicator shows up on the right side
It also uses the small prop from the button

Activity Indicator on Button Element Issue

---

src/buttons/ButtonGroup.js

The `containerStyle` should style the border around button group according to the documentation.
> containerStyle	inherited styling	object (style)	specify styling for main button container (optional)
It doesn't work, because it's on component and there is no other way to change the border's color.

Fix styling prop for ButtonGroup

---

src/buttons/Button.js
src/buttons/ButtonGroup.js
src/containers/Card.js
src/form/FormInput.js
src/form/FormLabel.js
src/helpers/normalizeText.js
src/input/Search.js
src/list/ListItem.js
src/pricing/PricingCard.js
src/text/Text.js

Fix #67 with helper function to normalize text size across devices.
Tested:
Devices:  iphone 5, iphone 5s, iphone 6, xiaomi 4, xiaomi 5
Simulators:  iphone 6s, iphone 6s plus, iphone 7, iphone 7 plus, Samsung Galaxy S4
This still needs some work to catch all android devices and get all ratios equal but hopefully decent starting point.

Add normalize text helper function

---

src/icons/Icon.js

Got a warning when I try to use style created via StyleSheet.create. This PR fixing it.
I also double checked propTypes for rest components - they haven't this issue because all propTypes are correct (equal to PropTypes.any).
Let me know if you have any questions.

Fix propTypes for Icon component

---

Readme.MD
src/pricing/PricingCard.js

I noticed when using the PricingCard component that I was unable to pass an onPress function to the component's button. This fixes that! 
Thanks for the great lib.

Pass onButtonPress prop to PricingCard Component

---

src/buttons/Button.js

The TouchableWithoutFeedback prop `hitSlop` was missing from button. This adds that.
https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#props

[FIX] add hitSlop to button

---

src/buttons/ButtonGroup.js

By default, ButtonGroup elements convert the text labels to upper case. Since react native doesn't support text transforms via css styles (and they'd be overwritten anyways by the button.toUpperCase() call, can we not force the upper casing on all text and instead just pass through the initial button text labels?

ButtonGroup text labels shouldn't force upper case

---

src/index.js

Slider Component was introduced in v0.9.0 but it was not exported.

Fixed missing Slider Component

---

Readme.MD

`rightIcon` will be hidden only if `hideChevron` is set after PR #166 was merged to master.

Updated ListItem in README

---

using-with-crna.md

The previous asset system issue has been fixed -- CRNA apps created as of last night can now load ttf by default.

Update using-with-crna.md -- TTF fonts are recognized by default now

---

using-with-crna.md

Since `yarn add` command adds installed package to project dependencies, we should add a save param to the `npm install` command so they are both equal.

Add missing save param to the npm install command in CRNA readme

---

src/checkbox/CheckBox.js
src/config/fonts.js
src/containers/Card.js
src/form/FormLabel.js
src/list/ListItem.js
src/pricing/PricingCard.js
src/social/SocialIcon.js
src/text/Text.js

It turns out the previous commit almost fixed it but in a few places it was necessary to add fontWeight rather than specify it as fontFamily.

Use fontWeight and fontFamily rather than fontFamily for everything

---

README.md
src/containers/Card.js

Fixes the bug introduced in commit #200 where we are no longer able to set flex for image and wrapper, as the parent View component has no flexbox. With this, a style of `{flex: 1}` can once again be set on the View. 
Addresses issue #259

ImageWrapperStyle prop for Card component to fix card image flex

---

README.md

Link doesn't work without https:// in front

Fixing Link for create react native

---

src/avatar/Avatar.js

Currently when setting a width and/or height for an Avatar, the iconSize and titleSize don't update unless they are explicitly set.
This allows a user to set their own width and height for an avatar, and have the iconSize and titleSize adjust accordingly.

Avatar - default iconSize and titleSize to half of width

---

package.json
src/buttons/ButtonGroup.js
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap

ButtonGroup: when the first or last button is selected (has a background color), the overflow on Android is broken, causing square corners. This problem does not affect iOS.
Before:
After:
This fix allows a border radius on the button which can work-around the issue.
A better solution would be to fix overflow in Android in react-native core. There is an open issue for that but no ongoing work at this time (as per the documentation).

Fix android overflow: ButtonGroup

---

docs/API/badge.md
src/badge/__tests__/__snapshots__/badge.js.snap
src/badge/__tests__/badge.js
src/badge/badge.js
src/index.js

- Included the badge prop's properties as top level props, intended to be used going forward
- Kept the 'badge' prop intact for backwards compatibility

Fix #206 - Export Badge as separate component

---

src/input/Search.js
src/input/__tests__/Search.js

The response on the react issue was to change the code to make the behavior work. https://github.com/facebook/react-native/issues/13251
This calls onChangeText when the clearButton is pressed, as expected.
I also added unit tests for this.
Closes https://github.com/react-native-training/react-native-elements/issues/234

added test for search clearInput, closes #234

---

package.json

This is will remove the annoying (but harmless) error message that some experienced after npm install (Fixes #335)

Update open collective postinstall script

---

docs/API/lists.md
src/list/ListItem.js

This is to obscure any sensitive input in the textInput field such as passwords. Using the ListItem elements for a custom account page, I found secureTextEntry prop missing to be able to use it for passwords without implementing the component myself.

add secureTextEntry prop for sensitive text

---

package.json

See: [https://github.com/react-native-training/react-native-elements/issues/353](https://github.com/react-native-training/react-native-elements/issues/353)

Set react-native-vector-icons to 4.1.0

---

package.json
src/social/SocialIcon.js

I get a warning message on socialIcon component when using fontStyle prop.
Wondering if prototype for fontStyle should be Text instead of View. 
Submitting a PR with this change, can you please review.

fix(socialIcon): fontStyle prototype to Text

---

src/buttons/Button.js
src/buttons/__tests__/__snapshots__/Button.js.snap

This PR addresses https://github.com/react-native-training/react-native-elements/issues/350 and adds two more styles. Also for convenience while prototyping I opted for having a stylesObject which I'm using to access nested style properties (like stylesObject.text.fontSize) rather than moving properties into separate keys in a StyleSheet (like styles.textFontSize). I don't know if you'll be ok with this solution.

Add button styles (transparent, outline, rounded)

---

src/input/Search.js
src/input/__tests__/__snapshots__/Search.js.snap

Old: 
News:
1. clearIcon && showLoadingIcon 
2. clearIcon && !showLoadingIcon
3. !clearIcon && showLoadingIcon
this PR fix #263 .
cc @binoy14 , @Monte9

Fix SearchBar overlapped issue

---

src/input/Search.js
src/input/__tests__/__snapshots__/Search.js.snap

Yo
Just a quick fix for the SearchBar component on Android. I noticed that the clear button and the loading icon are not centered.
The loading icon was just 1 pixel far from the center (so close 😢), but the clear button was clearly not centered.
Before :
After : 😀
Here are the modifications:
And, I use the same style `icon` for the two icons `clear` and `search` to avoid duplication because they have the same layout configuration.
Tell me if there is anything to change, thanks ! 🌵💩

Fix SearchBar icons alignement on Android

---

src/buttons/ButtonGroup.js
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap

ref: https://github.com/react-native-training/react-native-elements/issues/364
There is a bug left…
It’s only happen if you juste have 2 buttons on your buttonGroup, the border will still be missing.
Because the 2 buttons will have a borderRadius, so the border will not be displayed…
Or we can wait the fix by react-native ([issue](https://github.com/facebook/react-native/issues/8236))
(PS: I put the default radius of start & end buttons to 3, like the container radius)

Fix missing border on ButtonGroup

---

docs/API/header.md
docs/API/slider.md
docs/API/swipedeck.md

This fixes https://github.com/react-native-training/react-native-elements/issues/435 and also example images for Slider and SwipeDeck that weren't showing up.

Fix some example images not showing up in docs (Header, Slider, SwipeDeck)

---

docs/API/header.md

If you copy and paste the first example it will generate the follow warning: 
"Warning: Failed prop type: Invalid props.style key `color` supplied to `View`."
This minor fix corrects the issue.

Fixes invalid API doc which generates a RN warning

---

src/form/FormInput.js
src/form/__tests__/__snapshots__/FormInput.js.snap

I found bug with autoresize multiline text-input. Here is small fix for it.
Just try to write few lines of text in this input:
```js
<FormInput multiline />
```
You can see that it isn't resizing, when RN `<TextInput />` is.

fix autoresize for multiline text-inputs

---

src/index.js

Build with webpack will raise `Cannot assign to read only property 'exports' of object '#<Object>' (mix require and export)`, see https://github.com/webpack/webpack/issues/4039#issuecomment-273804003.

Fix mix of import and module.exports

---

docs/API/lists.md

For some props, column default and type was mixed up.
At the end, the default column was missing; at least added it empty not to break the table anymore...

fix props table

---

src/swipedeck/SwipeDeck.js

I found one more bug: `<SwipeDeck />` ignores move-gestures if card is `<TouchableOpacity />`.
```
<SwipeDeck
data={cards}
renderCard={this.renderCard}
onSwipeLeft={() => console.log('to repeat')}
onSwipeRight={() => console.log('known')}
/>
```
```
// Card
<TouchableOpacity
onPress={() => this.setState({
isFlipped: !this.state.isFlipped
})}
>
<Text>{title}</Text>
{ isFlipped && <Text>{content}</Text> }
</TouchableOpacity>
```
Here is small fix:

fix for touchable swipedeck

---

src/buttons/ButtonGroup.js

Currently, a fix in ButtonGroup allows passing a containerBorderRadius prop. The current implementation uses this: `containerBorderRadius || 3`, which means that if containerBorderRadius is 0, then it will display 3, not 0.
This is important because displaying a border radius when the background is a different color causes a visual artifact (pictured below, notice the white triangles in the corner).

Allow containerBorderRadius to equal zero for ButtonGroup

---

docs/API/button_group.md
src/buttons/ButtonGroup.js
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap

As I wasn't sure what practices you follow for snapshots, PR does not include updated snapshots so 5 tests are failing. 
If update to snapshots is not desired, line 53 could be modified to not output "disabled={false}" by default. 
Happy to resubmit with updated snapshots or modified to avoid problem if preference is provided.
● ButtonGroup Component › should render without issues
expect(value).toMatchSnapshot()
Received value does not match stored snapshot 1.
- Snapshot
+ Received
@@ -18,10 +18,11 @@
]
}
>
<TouchableHighlight
activeOpacity={0.85}
+    disabled={false}
onPress={[Function]}
style={
Array [
Object {
"flex": 1,
@@ -71,10 +72,11 @@
</TextElement>
</View>
</TouchableHighlight>
<TouchableHighlight
activeOpacity={0.85}
+    disabled={false}
onPress={[Function]}
style={
Array [ …

WIP: pr/ButtonGroup-DisableSelected

---

example/src/views/login/screen3.js
example/v1/input/Input.js

Hey !
Here is the shake input animation that @martinezguillaume did, but on the v1 input. 🔥 
I replicated the shake props logic, because I think using redux and stateless component it can be useful to pass directly the `error` object returned from an API call to the input, and it will shake itself if the `error` is `!==` from the previous one (and not falsy obviously).
I updated the `screen3`, as it is already animated it will fit perfectly.
Let me know if some changes are required ✌️ 
(It is quite laggy on a gif tho...)

Add shake animation to Input v1

---

src/tile/Tile.js

Adding 'numberOfLines' prop for Text component (used to display title) in Tile.js.
So users can set numberOfLines for their 'title' text.

Update Tile.js: adding 'numberOfLines' prop

---

docs/API/lists.md
src/list/ListItem.js

According to the spec
https://facebook.github.io/react-native/docs/textinput.html#keyboardtype
Here is an example with a `keyboardType={'email-address'}`
__Before:__
__After:__
The email keyboard appears 🎉

fix(FormInput): follow the official doc with keyboardType

---

src/buttons/Button.js
src/buttons/__tests__/__snapshots__/Button.js.snap

[issue #535](https://github.com/react-native-training/react-native-elements/issues/535), where to have a clean button you would also need to apply the
border radius value to the containerViewStyle prop so that the containing
view would wrap the rounded button. Test snapshots were updated to reflect
the change.

Fix(Button): Border Radius was not applied to view container.

---

src/buttons/Button.js

i kept iconRight's prop for compatibility but no longer needed.

Support right icon and left icon at the same time.

---

docs/API/buttons.md

`iconLeft` is not a valid prop for Button. This should be `leftIcon`.

Rename iconLeft to leftIcon in button docs api

---

package.json
yarn.lock

I am not too familiar with this project, using just a couple components of it. However, trying to use it with React@16 ended up with error of using `PropTypes` in the "old-way" in `react-native-side-menu`. I've noticed they have already released an update with that fixed. So far it seems this is only blocker to be React@16 compatible.

Update to React@16

---

src/tile/Tile.js
src/tile/__tests__/Tile.js
src/tile/__tests__/__snapshots__/Tile.js.snap

Closes #668 
Update Tile component to move the "resizeMode": "cover" from style to the new imageStyle prop so that there's no more warning message from ImageBackground

fix(Tile): remove resizeMode warning message

---

src/list/ListItem.js
src/list/__tests__/__snapshots__/ListItem.js.snap

Associated Issue: #547 
This fixes an issue where lists with different types of list items (some with badges or switches, and some without) have titles that do not line up horizontally. 
As more elements are added to a `ListItem`, the `titleSubtitleContainer` (with flex: 1) changes size. This causes `LeftIconWrapper`, `chevronContainer`, and `switchContainer` (each with flex: 0.15) to scale to 0.15 the size of `titleSubtitleContainer` throwing off horizontal alignment of elements.
Removing these lines fixes title alignment issue as well as alignment of chevron or `rightIcon` when `rightTitle` or `textInput` is added.
Before:
After:
The code I used to test: https://snack.expo.io/Skye7u10-

Fix horizontal alignment of ListItem elements

---

src/helpers/normalizeText.js

As per [this issue](https://github.com/react-native-training/react-native-elements/issues/659), a bug was found in which certain devices will return the pixel ratio as a float, breaking the font size normalization function. This PR fixes that.

Corrected normalizeText for certain Android devices

---

src/list/ListItem.js
src/list/__tests__/__snapshots__/ListItem.js.snap

Removes line that sets a flex width for `leftIcon`. This fixes alignment when there are several list items and some have chevrons and/or right titles, and some do not.
This line was removed in #675 but re-introduced by mistake when #671 was merged.

Fix ListItem flex alignment

---

docs/API/slider.md
src/slider/Slider.js
src/slider/__tests__/Slider.js
src/slider/__tests__/__snapshots__/Slider.js.snap

This PR adds a `orientation` props to the `Slider` component, as suggested here #748 
|props|type|default|
|------|----|-------|
|`orientation`|`"horizontal"` or `"vertical"`|`"horizontal"`|
|code|preview|
|-----|--------|
|`orientation="horizontal"`|`orientation="vertical"`|
|![dec-03-2017 13-40-46](https://user-images.githubusercontent.com/17592779/33525481-9d30fac2-d830-11e7-8799-275459e242f2.gif)|![dec-03-2017 13-40-03](https://user-images.githubusercontent.com/17592779/33525482-a44b5960-d830-11e7-9771-3bb75bd12e2e.gif)|

Vertical slider hotfixes

---

src/index.d.ts

Added missing Typescript `imageProps` declaration for `Card` component.

imageProps declaration for Card component

---

docs/API/buttons.md

The default color is #9E9E9E as specified in config/colors.js 
(and used in buttons as `colors.primary`: https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L273 )

Updated buttons documentation - backgroundColor

---

example/src/views/lists_home.js

The `height` prop in `Card` component were hiding the second View, limiting the View.
Style props in each child was also spared. This can be chest in the parent View.
This is more simple. I based of [Layout with flexbox](https://facebook.github.io/react-native/docs/flexbox.html)
emulator: `Genymotion`
before:
I just removed the `height` props and...
So.. I improved the adjustments and... (I use background props to see this modifications better)

Adjusted Avatars Card and children Views

---

docs/API/buttons.md
example/src/views/lists_home.js

`iconRight` throws up error on Android due to Boolean values in the API example

iconRight expects type `Object` not boolean

---

docs/API/button_group.md
example/src/views/lists_home.js
src/buttons/ButtonGroup.js
src/buttons/__tests__/ButtonGroup.js
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap

Greetings from Bulgaria,
Firstly - Thanks for the great framework.
I've found an issue with the button group and styling.
Since we want to allow the overwriting of styles for selected
button without the need of custom logic. This commit
allows that behavior by introducing a new property -
selectedButtonStyle.
Also include the change in the docs

Allow specifying of selectedButtonStyle in button group

---

src/list/ListItem.js

Fix error on empty rightTitle prop by adding `!!`

Fix ListItem

---

src/checkbox/CheckBox.js
src/checkbox/__tests__/__snapshots__/CheckBox.js.snap

Currently right now making a checkbox without text produces an ugly spacing and border around the component. This is caused because the styling for the text style is being applied.
This PR allows the checkbox to be ~an independent grown man~ able to display differently depending on if there's a title.

Separate checkbox single and checkbox with text styling

---

docs/API/button_group.md
src/buttons/ButtonGroup.js
src/index.d.ts

Closes #713
Adds the functionality to select multiple buttons on the button group.
Example:
```jsx
state = {
selected: [0]
};
render() {
return (
<View style={styles.container}>
<ButtonGroup
buttons={['Hey', 'Bop', 'Ha']}
selectMultiple
selectedIndexes={this.state.selected}
onPress={selected => {
this.setState({ selected });
}}
/>
</View>
);
}
```

feat(button-group): Adds selectMultiple feature

---

docs/API/searchbar.md

Minor documentation fix for an error I noticed while looking over the new SearchBar docs.

Fixed default clearIcon name in docs for SearchBar component.

---

src/header/Header.js

Ref https://github.com/react-native-training/react-native-elements/issues/813
Before: 
After:

fix(header): Alignment on android now consistent with iOS

---

website/pages/en/versions.js

Allows to view the latest changes in docs.

docs: Allow viewing `next` docs in version switch

---

docs/getting_started.md
website/versioned_docs/version-1.0.0-beta2/getting_started.md

Add `@beta` version in the instructions when you install react-native-elements, needed to follow the latest API.
Without this, users will install the latest "pre-1.0.0" version & some APIs change.

add beta version to getting started

---

src/input/Input.js

Part of #861 and prevents #952

Use `width: '100%'` for Input

---

website/pages/en/versions.js

Currently trying to select 0.19 on the website, redirects you 1.0.0-beta2 docs. This fixes that bug and allows you view 0.19 docs correctly.

Fix website versioning

---

website/package.json
website/static/css/custom.css
website/yarn.lock

The syntax coloring for code blocks on our website don't look great.
This is because the default syntax highlighter from Docusaurus it uses [highlight.js](https://highlightjs.org) which doesn't support JSX so the code blocks aren't so nice :\. 
This PR uses a commit by @brentvatne to use [prism.js](http://prismjs.com) as the highlighter instead of highlight.js until [custom syntax highlighters](https://github.com/facebook/Docusaurus/issues/438) are supported natively in Docusaurus.
**Before:**
**After:**

docs(website): Better syntax colouring for code blocks

---

website/versioned_docs/version-1.0.0-beta2/button.md

Soooo what happened is that the original docs from when we were using MKdocs had `title` on the button where it should've been `text`. Same for `textProps` and `textStyle`. 
See https://github.com/react-native-training/react-native-elements/blob/v1.0.0-beta2/docs/API/buttons.md.
This PR corrects the props to be `text` like they should've been.

docs(1.0.0-beta2): Correct prop on Button to be text

---

src/index.d.ts

* One liner - seems the `title` prop became `text` and was then reverted?

Update typings to match button title prop

---

src/index.d.ts

Revert `textStyle` to `titleStyle` and `textProps` to `titleProps`.

Update typings to match Button title props

---

src/index.d.ts

removed links and replaces JSX.Element React.ReactElement

---

docs/icon.md

Fixes the broken URL link in the documentation for adding custom icon fonts [here](https://react-native-training.github.io/react-native-elements/docs/icon.html#custom-icon-fonts)

Fix custom icon fonts example link

---

src/input/Input.js

fix(Input): avoid changing ref to text-input on every render
create `_inputRef` for Input object, pass it to the child text-input as ref, instead of creating a new ref function in every render.
Otherwise, in each render `this.input` becomes null for a while and that gets set again with the new ref function. 
That is due to the fact that React calls old-ref with null and new-ref with component when the ref function changes. Since, the ref function were being created in the render function, it used to change on every render.
Closes the following problem: input.focus() sometimes give the error `Cannot read the property of 'focus' of null`

Avoid changing ref function to the inner text input on every render (input sometimes becomes null, otherwise)

---

src/buttons/Button.js
website/versioned_docs/version-1.0.0-beta2/button.md

Now, the button is just limited to the "button" and not the container around it:
**Before :**
**After :**
It's more simple to use it
So, it's preferable to set the dimensions of the button in the `containerStyle` like the rest of our components: 
**Before :**
```js
<Button
title='LOG IN'
buttonStyle={{ height: 50, width: 250, backgroundColor: 'black' }}
containerStyle={{ marginVertical: 10 }}
/>
```
**After :**
```js
<Button
title='LOG IN'
buttonStyle={{ backgroundColor: 'black' }}
containerStyle={{ marginVertical: 10, height: 50, width: 250 }}
/>
```
(1000e pr 🎉)

Fix Button width (+ small refactor)

---

src/buttons/Button.js

Fixes (#639 , #771 , #901) by not adding redundant `<Text/>` component with `styles.title.padding = 8` if title is empty.

Remove Text from Button if title is empty

---

docs/input.md
src/index.d.ts
src/input/Input.js

Refs #892 
Associated PR for the example app: https://github.com/react-native-training/react-native-elements-app/pull/48
* `label` adds a label on top of the Input
* `labelStyle` adds style to the label
* Remove useless `displayError` props. If the `errorMessage` is not null, I suppose there is an error to display…
I basically took back the style of the old `FormLabel`

Add `label` for the Input component

---

src/tile/FeaturedTile.js
src/tile/Tile.js

As stated in the title and from the discussion on slack, we're trying to solve an error showing up inside production builds for web.
Should be implemented a null check on the component as written in the attached issue #960
haven't got much time right now. 
This should also resolve problems to people that are using react styleguidist like me. Here the other related issue that I opened there: https://github.com/styleguidist/react-styleguidist/issues/913

Solving imgSource propType undefined in Tiles

---

docs/avatar.md
src/avatar/Avatar.js
src/index.d.ts

Refactor Avatar Size props

---

docs/input.md
docs/searchbar.md
src/helpers/nodeType.js
src/helpers/renderIcon.js
src/helpers/renderNode.js
src/input/Input.js
src/searchbar/SearchBar-android.js
src/searchbar/SearchBar-default.js
src/searchbar/SearchBar-ios.js
src/searchbar/__tests__/SearchBar-android.js
src/searchbar/__tests__/SearchBar-default.js
src/searchbar/__tests__/SearchBar-ios.js
src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap

The default searchbar had to be refactored to have the same props as the platform specific ones
Moreover, I think it's still good to support the object icons as we had in `< 1.0.0`.
The `renderIcon` helper (inspired by @martinezguillaume in the `ListItem`) should help to handle icons in every components.
**Usage**
```
renderIcon(iconProps, { ...yourDefaultIcon })
```
**Behavior**
- `iconProps={false}`: default icon won't be rendered
- `iconProps={null}`: default icon won't be rendered
- `iconProps` or nothing: default icon will be rendered with all default props
- `iconProps={{ size: 20 }}` icon will be rendered with an overridden size
- `iconProps={{ type: 'material', name: 'close' }}` icon will be rendered with a custom type and name (keep the default color and size)
- …

Refactor and make uniform all SearchBars

---

.travis.yml

Node 10 currently breaks builds cause of missing whitelist console in react native jest setup. https://github.com/facebook/jest/issues/2567#issuecomment-384487860 Pinning node version until react-native/jest bumps
Required for #1156 to deploy.

ci(travis) Pin version of node

---

website/versioned_docs/version-0.19.0/button.md

for 0.19.0 `Button`
the `loading` item in props list is duplicate

Doc improvement: remove duplicate item

---

src/index.d.ts
src/searchbar/SearchBar-default.js
src/searchbar/SearchBar-ios.js
website/versioned_docs/version-1.0.0-beta4/searchbar.md

Cleanup SearchBar typings into:
* SearchBarWrapper(only `platform` prop)
* SearchBarBase (props used on all SearchBars)
* SearchBarDefault (props used only on `platform="default"`)
* SearchBarPlatform (props used on `platform="ios|android"`)
* SearchBarAndroid (props used on `platform="android"`) 
Also added missing `inputContainerStyle` to docs. (Fixes #1123)

Cleanup SearchBar typings and docs

---

website/versioned_docs/version-0.19.0/lists.md

for version 0.19.0 `Lists`
both `List` and `ListItem` have `containerStyle` props, however the two items link to the same url hash (#containerstyle)

Doc improvement: fix url hash conflict

---

src/input/Input.js

- Moves the ```underlineColorAndroid``` prop above the spread attributes on Input component.
[Underline Color](https://github.com/react-native-training/react-native-elements/issues/1200)

Update Input props for Android underline color

---

docs/pricing.md
src/index.d.ts
src/pricing/PricingCard.js
src/pricing/__tests__/PricingCard.js
src/pricing/__tests__/__snapshots__/PricingCard.js.snap

Refactor PriceCard props to accept style objects

---

src/pricing/PricingCard.js
src/pricing/__tests__/PricingCard.js
src/pricing/__tests__/__snapshots__/PricingCard.js.snap

As per documentation[1] the PriceCard should be able to work without any content in the info props, this fails because there is no condition check for its value before its its mapped.
*Updated test case for minimum props : removed 'info' as it should work without info.
[1] https://react-native-training.github.io/react-native-elements/docs/0.19.0/pricing.html
Performing PR on branch next as requested on #1246

Allow PricingCard to render without info prop

---

website/pages/en/index.js

View Components button was redirecting users to the beta components when it should go to 0.19.0
Addresses https://github.com/react-native-training/react-native-elements/issues/855#issuecomment-402811151

docs(website): Fix view components link on home page

---

src/buttons/ButtonGroup.js
src/buttons/__tests__/ButtonGroup.js
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap

Before the borders were applied on the touchable. So when the user taps on a TouchableOpacity for example, the border would blink as well. This PR wraps the touchable in a View and applies the border to the View.
Before when setting `innerBorderStyle={{ width: 0 }}`; the border would still remain. This is because the logic for the innerBorderStyle was faulty, as comparing `innerBorderStyle && innerBorderStyle.width` would always be false if the width is 0 since in Javascript the 0 will be coerced to false. This PR fixes the logic by using object.hasOwnProperty to correctly check if the width was passed. Inspired by #1274. Fixes #1300.

ButtonGroup fixes

---

src/input/Input.js

Addressed #1136 by checking for an empty string as well as null using the !! (not not) operator.

Fixed <Input> bug that caused errorMessage and label to render an empty string outside of <Text>

---

src/index.d.ts
src/input/Input.js

As per other component methods (focus(), blur()) etc that are passed-through from the contained React Native component, this will simply return the result of isFocused() in that component.

Hoist the isFocused() method from the react native input element

---

src/searchbar/SearchBar-default.js
src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap

(SearchBar) Allow containerStyle to override lightTheme styles

---

src/index.d.ts

🖖 Heya. The `size` prop was missing in CheckBox's type defs.

fix: add missing "size" prop to CheckBox types

---

website/versioned_docs/version-0.19.0/lists.md

Using index as a key is a bad practice and should be avoided. Please see https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318 for details.
Since many devs would just copy and paste the code, I believe it is exceptionally important to promote good practices in the docs.

Do not use index as a key

---

docs/icon.md
src/header/__tests__/__snapshots__/NavButton.js.snap
src/icons/Icon.js
src/icons/__tests__/Icon.js
src/icons/__tests__/__snapshots__/Icon.js.snap
src/index.d.ts
src/list/__tests__/__snapshots__/ListItem.js.snap
src/pricing/__tests__/__snapshots__/PricingCard.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
src/tile/__tests__/__snapshots__/Tile.js.snap

Adds `disabled` and `disabledStyle` props to the Icon component. 
Ideally, we should do this for all our interactable components. It's a common use case for like forms, where when submitting the fields are disabled.
Usage:
```jsx
<Icon disabled />
<Icon disabled disabledStyle={{ backgroundColor: 'pink' }} />
```

feat(Icon): Add disabled and disabledStyle

---

docs/rating.md
src/index.d.ts
src/rating/Rating.js

When using a rating component inside a ScrollView on iOS, the scrollview don't lock the scroll causing the rating component to get very laggy.
The onStartRating callback is useful on iOS because I can lock the scroll via the scrollEnabled prop on the start rating callback.

On start rating event

---

src/list/ListItem.js

Android crashes when using `rightTitle || rightSubtitle` to test if the values are present. Instead, we should make sure the value of those props are cast to Booleans before we check.
Closes #1391

fix(ListItem): Don't display empty rightTitle or rightSubtitle

---

website/versioned_docs/version-0.19.0/card.md
website/versioned_docs/version-1.0.0-beta3/card.md

People were getting errors copying and pasting these snippets since they
don't have Lato installed

docs(Card): Remove Lato fontFamily from examples

---

src/list/ListItem.js

Currently there is no styling for `ListItem` in `react-native-web` (and other platforms) because they are only applied to `android` and `ios`.
I changed `android` to `default` so android style is applied.
`react-native-web` example:
Before:
After:

[ListItem] Add android as default for list styling

---

docs/input.md
src/index.d.ts
src/input/Input.js
src/input/__tests__/Input.js
src/input/__tests__/__snapshots__/Input.js.snap

- Adds initial unit test for the `Input` component,
- Closes #1408 (support for `inputComponent` prop to pass a custom `TextInput` compatible component)
Thanks!

feat(Input): add inputComponent prop (closes #1408)

---

package.json
yarn.lock

The `opencollective` dependency is huuuuuuuge ([**11.6 MB**](https://packagephobia.now.sh/result?p=opencollective)). This patch replaces it with the officially supported smaller package which is just the postinstall hook:
https://github.com/opencollective/opencollective-postinstall

package: Use opencollective-postinstall for smaller install size

---

docs/searchbar.md

* Adds documentation for `leftIconContainerStyle` and `rightIconContainerStyle` which were added back in January of 2018 (Ref: #837).
Fairly trivial.  Attempted `npm test` but there are unrelated failures per your contributing guidelines.

[docs] add left/right icon containers to readme

---

docs/header.md
website/versioned_docs/version-1.0.0-beta6/header.md

It shouldn't be `containerstyle` but `containerStyle`.

Fix Header docs typo

---

package.json

Fix #1464 
RNVI dep:
```
λ cat package.json | grep vector-icons
"react-native-vector-icons": "^6.0.2"
```
**Tested locally.**
_Before:_
```
λ yarn add https://github.com/haruelrovix/react-native-elements#1464-rnvi-dependency
yarn add v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-native > metro > babel-preset-fbjs > @babel/plugin-check-constants@7.0.0-beta.38" has incorrect peer dependency "@babel/core@7.0.0-beta.38".nstants@7.0.0-beta.38" has incorrect peer dependency "@babel/core@7.0.0-be0 || ^7.0.0-0".ta.38". …
```

Use 'Must be greater than version' for RNVI dependency

---

src/config/ThemeProvider.js

updateTheme uses lodash.merge. merge is a mutative operation which
error as it was trying to mutate a value on state.
Closes #1522

fix: Change updateTheme to merge empty object first

---

docs/tile.md
src/tile/FeaturedTile.js
src/tile/Tile.js
src/tile/__tests__/FeaturedTile.js
src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
website/versioned_docs/version-1.0.0-beta6/header.md

PR created to solve [issue #1415](https://github.com/react-native-training/react-native-elements/issues/1415) created by [beltrancaliz](https://github.com/beltrancaliz)
I've added possibility to pass object as propTypes to Tile/FeaturedTile instead of passing only simple string.
Also `captionStyle` won't work if you'll pass an object, because you can style it without this prop :)

feat(Tile): Allow caption to be a React element

---

src/buttons/Button.js
src/buttons/__tests__/__snapshots__/Button.js.snap
src/pricing/__tests__/__snapshots__/PricingCard.js.snap

They have the same `height` now.
|Before|After|
|-|-|
|![screenshot_2018-10-23-22-09-11-543_com a](https://user-images.githubusercontent.com/17120764/47373555-49ab1000-d716-11e8-9f5e-d810f9ab44d5.png)|![screenshot_2018-10-23-22-39-29-935_com a](https://user-images.githubusercontent.com/17120764/47373563-4fa0f100-d716-11e8-90c5-d5448cb457dc.png)|
Fix #1427 .

fix(Button): Make the padding consistent

---

docs/avatar.md
docs/checkbox.md
docs/icon.md
docs/tile.md

Right now it's kind of annoying everytime react-native-vector-icons adds a new font family, that we have to update the list of fonts we support in multiple places.
This change list all the available fonts on the icon page.

docs(website): Add central place to show supported icon sets

---

src/buttons/Button.js
src/buttons/__tests__/__snapshots__/Button.js.snap
src/pricing/__tests__/__snapshots__/PricingCard.js.snap

Creating roudned buttons with custom height, width had graphical bugs on
android
BREAKING CHANGE: Default Button on android has no elevation
Closes #1537

fix: Rounded buttons on android now work correctly

---

docs/avatar.md
docs/tooltip.md

I've noticed that some links doesn't work in docs when I want to access specific paragraph, so... here is fixed version :)

Fix: paragraphs links in docs

---

src/searchbar/SearchBar-android.js
src/searchbar/SearchBar-default.js
src/searchbar/SearchBar-ios.js

Changed the code to take into account when a value has been set on the props of the SearchBar.
Fix for this issue https://github.com/react-native-training/react-native-elements/issues/1247

Check to make sure that the SearchBar is really empty

---

docs/image.md
src/image/Image.js
src/image/__tests__/Image.js
src/image/__tests__/__snapshots__/Image.js.snap
src/index.d.ts
src/index.js
website/i18n/en.json
website/sidebars.json
website/static/css/components.css

Implements #1478 
Adds Image component that has support for placeholders. Basically takes out the FadeInImage component that @martinezguillaume wrote in https://github.com/react-native-training/react-native-elements/commit/f8af41c1959625c1d3679a88ad9437059abe39aa and splits it into it's own component.
A follow-up PR will let the Avatar component use this.
```js
import { ActivityIndicator } from 'react-native';
import { Image } from 'react-native-elements';
// Standard Image
<Image
source={{ uri: image }}
style={{ width: 200, height: 200 }}
/>
// Image with custom placeholder content
<Image
source={{ uri: image }}
style={{ width: 200, height: 200 }}
PlaceholderContent={<ActivityIndicator />}
/>
```

feat: Add Image component

---

src/index.d.ts

This type is missing. The example of the changelog for the `<ListItem />`:
```ts
// Before
<ListItem checkmark checkmarkColor="red" />
// After
<ListItem checkmark={{ color: 'red' }} />
```
Currently throws an error. After this fix, it doesn't anymore.

Add TextStyle to possible checkmark types.

---

.travis.yml
package.json

Hello,
Since all eslint errors have fixed in #1599, i guess we can safely add eslint check to pre-commit hook and travis pipeline

test: Add lint to ci pipeline and pre-commit hook

---

src/overlay/Overlay.js

Currently there is no consistent style applied to components for `react-native-web` (platform `web`), electron (platform `desktop`) and all others expect `ios` and `android`.
`react-native` supports the platform `default` which means it takes the value default if its not overridden by a specific platform.
This PR sets iOS as default style for `Overlay`.

feat(Overlay): Support RNW with iOS style as default

---

src/social/SocialIcon.js

Currently there is no consistent style applied to components for `react-native-web` (platform `web`), electron (platform `desktop`) and all others expect `ios` and `android`.
`react-native` supports the platform `default` which means it takes the value default if its not overridden by a specific platform.
This PR sets iOS as default style for `SocialIcon`.

feat(SocialIcon): Support RNW with iOS style as default

---

src/buttons/Button.js
src/buttons/ButtonGroup.js

Currently there is no consistent style applied to components for `react-native-web` (platform `web`), electron (platform `desktop`) and all others expect `ios` and `android`.
`react-native` supports the platform `default` which means it takes the value default if its not overridden by a specific platform.
This PR sets iOS as default style for `Button` and `ButtonGroup`.

feat(Button&ButtonGroup): Support RNW with iOS style as default

---

package.json
src/header/Header.js
yarn.lock

Currently there is no consistent style applied to components for `react-native-web` (platform `web`), electron (platform `desktop`) and all others expect `ios` and `android`.
`react-native` supports the platform `default` which means it takes the value default if its not overridden by a specific platform.
This PR sets iOS as default style for `Header`. (44px header size looks nice)

feat(Header): Support RNW with iOS style as default

---

src/image/Image.js
src/image/__tests__/Image.js

Currently there is no consistent style applied to components for react-native-web (platform web), electron (platform desktop) and all others expect ios and android.
react-native supports the platform default which means it takes the value default if its not overridden by a specific platform.
This PR sets iOS as default style for Image.
This fixed the currently not working fade in animation.

feat(Image): Support RNW with iOS style as default 

---

src/config/fonts.js

This PR fixed possible null pointers for platforms other than `android` and `ios`. It returns an empty object as default fonts value.

feat(config/fonts): Support RNW with empty defailt fonts

---

src/searchbar/SearchBar-android.js
src/searchbar/SearchBar-default.js
src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap

This PR changes the `SearchBar` icons from `material-community` to `material`.
The default icon is `material`. We should use it here too, so RNW does not have to load two fonts just because the `SearchBar` uses another one than the default.
This increases the performance of the app and needs less network traffic, because only one font is needed by default.
Question: Do we need it and should we change it in SearchBar.android too?

fix(SearchBar): Switch from material-community to material

---

docs/header.md
src/header/Header.js
src/header/__tests__/Header.js
src/header/__tests__/__snapshots__/Header.js.snap
src/index.d.ts

Issue: #1551 
Added possibility to pass `backgroundImage` prop which is simply `source` prop like in `Image` component :) e.g. :
```
source={{ uri: 'http://google.com' }}
```

feat(Header): Add background image

---

src/list/ListItem.js
src/list/__tests__/__snapshots__/ListItem.js.snap

Allow all ListItem right-sided props (rightTitle, rightElement) to
display correctly aligned to the right even when title is not provided.
Closes #1605

fix(ListItem): Allow solo rightTitle to display correctly

---

docs/card.md
src/card/Card.js
src/card/__tests__/Card.js
src/card/__tests__/__snapshots__/Card.js.snap
src/index.d.ts

Deprecates two props:
`fontFamily` - Can be set through `titleStyle`
`flexDirection` - Can be set through `wrapperStyle`

Remove unnecessary props from Card

---

src/text/Text.js
src/text/__tests__/Text.js
src/text/__tests__/__snapshots__/Text.js.snap

Props like h1, h2 not working if the the font size in the theme was set.
This is because of the order in which the styles were applied. To fix
this we should apply the style prop first then the other props like h1,
h2 etc.
Closes #1663

fix(Text): Allow local props to override theme set font size

---

src/index.d.ts

`ListItem`'s `checkBox` props in `index.d.ts` is misspelled. It should be [`checkBox`](https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L332) not [`checkbox`](https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L1049).

fix(types): Fix ListItem checkBox props typo

---

src/searchbar/SearchBar-android.js
src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap

Before the searchbar was using a static width of the screen. Even when overriding this width to auto or 100% - margins being applied to the container would never show.
Closes #1699
```jsx
<View
style={{
flex: 1,
backgroundColor: 'pink',
alignItems: 'center',
justifyContent: 'center',
}}
>
<SearchBar
platform="android"
containerStyle={{ marginHorizontal: 30 }}
showLoading
/>
</View>
```
You can see there the loader is off the screen
```jsx
<View
style={{
flex: 1,
backgroundColor: 'pink',
justifyContent: 'center',
}}
>
<SearchBar
platform="android"
containerStyle={{ marginHorizontal: 30 }}
showLoading
/>
</View>
```
It's only by setting `width: null` on both the `containerStyle` and `inputContainerStyle` that this can be achieved.
```jsx
<View
style={{
flex: 1,
backgroundColor: 'pink', …
```

fix(SearchBar Android): Allow margins to be added to containerStyle

---

src/searchbar/SearchBar-ios.js
src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap

The horizontal margins on the ios SearchBar are too inset when unfocused and when focused is not the same as the cancel button margin. This PR aligns the container to have the correct margins.

fix(SearchBar iOS): Align margins closer to native searchbar

---

src/avatar/Avatar.js
src/avatar/__tests__/Avatar.js
src/avatar/__tests__/__snapshots__/Avatar.js.snap

Placeholder style (grey background) was showing even when not
using source, which resulted with the avatar having a grey
background when using the icon prop by itself or the title prop.
This commit fixes this behavior and allows users to use the
correct prop to style the background - `overlayContainerStyle`
Fixes: #1705

fix(Avatar): Don't show placeholder style if not using source

---

src/input/Input.js
src/input/__tests__/__snapshots__/Input.js.snap
src/searchbar/SearchBar-default.js
src/searchbar/SearchBar-ios.js
src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap

Inputs were set a fixed height. Meaning if the developer increases the fontSize of the input, it would result in a scrollable area in the text field. Also if users had on display scaling for accessibility reasons, then they'd be unable to view the text.
This PR changes the fixed height to minHeight to allow scaling.
Fixes #1239
---
Examples below are with `inputStyle={{ fontSize: 100 }}`

fix(SearchBar|Input): Allow height on fields to scale with fontSize

---

docs/customization.md

There is a small typo in the [Customization](https://react-native-training.github.io/react-native-elements/docs/customization.html) docs. The docs talk about the precedence of styling components in React Native Elements. The example shows how theming a `<Button />` with props overrides the them set by the `<ThemeProvider />`. The typo lies in the fact that a `<Card />` is being styled instead of a `<Button />`. This fixes that. 😃

Fix small typo in customization docs

---

src/index.d.ts

[The docs](https://react-native-training.github.io/react-native-elements/docs/image.html) are accurate about the usage of this `PlaceholderContent` prop:
```js
<Image
source={{ uri: image }}
style={{ width: 200, height: 200 }}
PlaceholderContent={<ActivityIndicator />}
/>
```
i.e. you provide a `ReactElement`, not a `ComponentType` as specified in the TypeScript definitions here.
[Examining the source](https://github.com/react-native-training/react-native-elements/blob/master/src/image/Image.js#L69) shows that it's used as a `ReactElement` too. i.e. rendered directly rather than a Component:
```js
>
{PlaceholderContent}
</Animated.View>
```

Fix PlaceholderContent type

---

src/index.d.ts

`ListItem` props `chevron` and `checkmark` [are rendered](https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L213):
```js
{renderNode(Icon, checkmark, checkmarkDefaultProps(theme))}
{renderNode(Icon, chevron, chevronDefaultProps)}
```
Using the [`renderNode` helper](https://github.com/react-native-training/react-native-elements/blob/master/src/helpers/renderNode.js), which includes the option of a `ReactElement`:
```js
const renderNode = (Component, content, defaultProps) => {
if (content == null || content === false) {
return null;
}
if (React.isValidElement(content)) {
return content;
}
```

Add ReactElement<{}> to ListItem.chevron and checkmark

---

src/index.d.ts

From `src/config/colors.js`: https://github.com/react-native-training/react-native-elements/blob/next/src/config/colors.js#L19

Added divider color in TypeScript definition

---

package.json
src/config/ThemeProvider.js
src/config/withTheme.js
yarn.lock

While using ThemeProvider, some errors would be shown for some
components for arrays not having keys. This was due to the merge
algorithm in lodash.merge which happens to affect react's keys.
Switching to deepmerge instead of lodash.merge does not have this
issue but maintains expected behaviour.
Fixes #1735 #1517

fix: Change merge library to deepmerge from lodash

---

docs/text.md
src/index.d.ts
src/text/Text.js

Allows user to set the styling that should be applied when props
h1, h2, h3, h4 are used.
Implements #1754

feat(Text): Add style props to customize header props

---

src/index.d.ts

Added `underlayColor` to the `SocialIconProps` interface.
I wasn't sure as for what to write as a default, since it is only white if the button is light and the default color varies according to the button type.

fix: add underlayColor to SocialIconProps interface

---

src/buttons/Button.js

According to the #1787 the ripple of TouchableNativeFeedback in Button will overflow out of box due to value of borderless variable & it changed in this pull request.

Fix button out of border ripple

---

docs/listitem.md

The value of keyExtractor must be a string. -[related issue](https://github.com/facebook/react-native/issues/18291)
Now the warning like below appeared.
```
Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`.
```

The value of keyExtractor must be a string

---

docs/getting_started.md

"As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. The other save options still exist and are listed in the documentation for npm install."
https://stackoverflow.com/a/19578808/142358

Remove --save option from npm install

---

src/index.d.ts

This allows use to use a `FunctionComponent` and not just a class

fix: make ImageComponent a ComponentType

---

src/buttons/Button.js

The first argument of TouchableNativeFeedback.Ripple function takes a color as a string.
https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableNativeFeedback.android.js#L169

fix(Button-android): remove wrong color argument

---

docs/tooltip.md
src/index.d.ts
src/tooltip/Tooltip.js

- Adds a prop to the toolTip to change the overlay background color. If there is a prop to add an overlay, there should be a prop to change the color of that overlay. #1827
- We are using the tool tip as a floating action button, on an app that our customers can theme(with their branding). Currently the users would only see the default white and this would cause issues. 
- Users can still change the opacity if they want
- Expected: If I change the color of the overlay color to red the user will see a red background/shadow to the overlay.
- Actual: We(library users) can't change the color so we are stuck with the default white.

Add overlayColor prop to toolTip for users to set the background color

---

.npmignore

The npm package in the current version (1.1.0) contains the `website` folder, which increases the package size from ~1MB to 33MB. Additional files can probably be ignored, too.

Ignore folders from npm package

---

src/index.d.ts

Hello,
Some small change
I can't assign function component to `Input.inputComponent`. This change should fix that.
Sample:
```.tsx
private renderEmailInput = (props: any) => {
return <TextInput {...props} editable={!this.isFieldDisabled('email')} />;
};
```
@iRoachie can you code review? Ty in advance.

Allow function components to Input.inputComponent

---

.eslintignore
package.json
src/index.d.ts
webpack.config.js
yarn.lock

Since typescript is supported by @react-native-community eslint package (https://github.com/react-native-training/react-native-elements/commit/3224d9a822c26a2adecba3858720217a19c134a6), we can lint the ts file as well.

ci: Allow linting of typescript definitions

---

src/buttons/ButtonGroup.js
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap

Just a minor fix :). The color object should be converted to a string as per [color lib's](https://www.npmjs.com/package/color) docs;
This is the runtime exception I encountered.
```
ExceptionsManager.js:82 
Warning: Failed prop type: Invalid prop `color` supplied to `TextElement`: [object Object]
Valid color formats are
- '#f0f' (#rgb)
- '#f0fc' (#rgba)
- '#ff00ff' (#rrggbb)
- '#ff00ff00' (#rrggbbaa)
- 'rgb(255, 255, 255)'
- 'rgba(255, 255, 255, 1.0)'
- 'hsl(360, 100%, 100%)'
- 'hsla(360, 100%, 100%, 1.0)'
- 'transparent'
- 'red'
- 0xff00ff00 (0xrrggbbaa)
Bad object: {
"fontSize": 16.51,
"color": {
"model": "hsl",
"color": [
208,
8,
63
],
"valpha": 1
},
"fontWeight": "500"
}
```

Fix ButtonGroup color runtime exception

---

src/index.d.ts

Resolves #1912
Extends the `IconProps` interface from react-native-vector-icons `IconButtonProps` so it includes accessibility props.

feat(types): Allow accessibility props on Icon

---

src/searchbar/SearchBar-ios.js

Fixes #1977
Also clears the text in the input as is the native behavior on iOS

fix(SearchBar-ios): Hide clear icon on cancel

---

package.json
src/searchbar/SearchBar-ios.js
src/searchbar/__tests__/common.js

Changes in https://github.com/react-native-training/react-native-elements/commit/78ff4d81ee4b71a312a16a775b9438971a9280a8 mean that sometimes the JS thread will update the UI based on the onChangeText callback and do the layout animation for the SearchBar together.
This results in any content that depends on the onChangeText callback getting this animation applied. This fix allows the onChangeText callback and the blur to run in different frames.

fix(SearchBar-ios): Stop layoutAnimation effects

---

docs/input.md
src/index.d.ts
src/input/Input.js
website/versioned_docs/version-1.0.0/input.md
website/versioned_docs/version-1.1.0/input.md

The shake prop only functioned as prop in v0.19x. Since v1 the shake functionality is done through refs. This commit updates the docs to show this usage as well as to remove the shake prop entirely.
Resolves #1883

feat(Input): Remove shake as prop usage

---

docs/customization.md
src/avatar/__tests__/__snapshots__/Avatar.js.snap
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
src/card/__tests__/__snapshots__/Card.js.snap
src/config/ThemeProvider.js
src/config/__tests__/ThemeProvider.js
src/config/__tests__/__snapshots__/ThemeProvider.js.snap
src/config/withTheme.js
src/divider/__tests__/__snapshots__/Divider.js.snap
src/header/__tests__/__snapshots__/Header.js.snap
src/icons/__tests__/__snapshots__/Icon.js.snap
src/image/__tests__/__snapshots__/Image.js.snap
src/index.d.ts
src/input/__tests__/__snapshots__/Input.js.snap
src/list/__tests__/__snapshots__/ListItem.js.snap
src/overlay/__tests__/__snapshots__/Overlay.js.snap
src/pricing/__tests__/__snapshots__/PricingCard.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
src/social/__tests__/__snapshots__/SocialIcon.js.snap
src/text/__tests__/__snapshots__/Text.js.snap
src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
src/tile/__tests__/__snapshots__/Tile.js.snap

to merge the theme passed in with the default theme.
The standard updateTheme function only allows to merge the passed in theme with the current theme.

Added replaceTheme function

---

src/buttons/ButtonGroup.js
src/index.d.ts

Allow selectedIndex to be null or optional. Will default to null if no value set.
Fixes #1852

fix(ButtonGroup): Correct type for selectedIndex

---

docs/input.md
src/index.d.ts
src/input/Input.js
src/input/__tests__/__snapshots__/Input.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap

Fresh PR for adding the disabled property to the Input component, based on the `next` branch.
Check previous PR for the full discussion: https://github.com/react-native-training/react-native-elements/pull/1904

Add disabled prop for Input component

---

src/searchbar/SearchBar-android.js
src/searchbar/SearchBar-default.js
src/searchbar/SearchBar-ios.js

- Updates the ```onFocus``` function in the Search Bar(iOS & Android) to set the state of the ```isEmpty``` prop to show the the Clear icon when the Search Bar becomes focused when an initial value is given.
- The search bar only sets the ```isEmpty``` state in the constructor and in the```onChangeText``` function. We ran into an issue were a value is given to the Search Bar(via redux/prop passing) after the Search Bars has already mounted, the user would focused the Search Bar and the clear icon would not be displayed until they changed the text in the input.
- Expected: As a user when I'm taken to a new screen with the search text/value is presented in the new Search Bar, and when I focus the search bar and I can press the the clear icon to start a fresh search.
-Actual: The user …

Add isEmpty check to onFocus of the Search Bar

---

package.json
src/input/Input.js

Fix for https://github.com/react-native-training/react-native-elements/issues/1901

fix(Input): allow to pass React.forwardRef as inputComponent (#1901)

---

docs/avatar.md
docs/card.md
docs/image.md
docs/tile.md
src/avatar/__tests__/__snapshots__/Avatar.js.snap
src/image/Image.js
src/image/__tests__/__snapshots__/Image.js.snap
src/index.d.ts
src/tile/FeaturedTile.js
src/tile/Tile.js
src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
src/tile/__tests__/__snapshots__/Tile.js.snap

Since https://github.com/react-native-training/react-native-elements/commit/e2795821fa85bbce48282b9c92d2260658d5c35e the Image component supports nesting children being based from ImageBackground. This meant however that children of the Image would not be visible until the image loaded which is incorrect behaviour.
This commit fixes this, allowing children to be visible while the image loads in the background. Also instead of using the ImageBackground component from react native, we implement our own based on [the source](https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageBackground.js). This is so we can place the animated placeholder between the content and the image.
e.g (background -> animated placeholder -> our content)
Also makes some small tweaks to Tile and …

feat(Image): Allow children to be displayed while image loads

---

src/index.d.ts

Added React.ComponentElement to match the accepted input types as stated in the [docs](https://react-native-training.github.io/react-native-elements/docs/input.html#label).

Added React.ComponentElement to input label type

---

src/image/Image.js

Fixes a bug where when the source on Avatar is set to null, then the title would never show.
```jsx
<Avatar title="MD" source={null} />
```
The result would just be grey. This is because the Image component was explicitly checking if attributes.source was 'undefined'.

fix(Image): Blank placeholder when source is null

---

docs/button_group.md
src/buttons/ButtonGroup.js

This PR addresses #1784 
I've removed containerBorderRadius from ButtonGroup docs,
and removed the containerBorderRadius from ButtonGroup component.

Remove containerBorderRadius props

---

src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
src/card/__tests__/__snapshots__/Card.js.snap
src/helpers/index.js
src/input/Input.js
src/input/__tests__/__snapshots__/Input.js.snap
src/list/__tests__/__snapshots__/ListItem.js.snap
src/pricing/__tests__/__snapshots__/PricingCard.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
src/text/Text.js
src/text/__tests__/__snapshots__/Text.js.snap
src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
src/tile/__tests__/__snapshots__/Tile.js.snap

Most properties are spread into native elements to pass properties directly. However, since some of these props aren't dom properties they error on react-native-web.
Fixes #1747

fix: Remove props from native components 

---

src/icons/Icon.js
src/icons/__tests__/Icon.js
src/icons/__tests__/__snapshots__/Icon.js.snap
src/pricing/__tests__/__snapshots__/PricingCard.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap

Allows using TouchableNativeFeedback on android, and TouchableHighlight on web and iOS.
None of the breaking changes below break your app, but the look might change depending on the props used.
BREAKING CHANGES:
- No longer uses TouchableHighlight on android by default.
- Default underlay color is now transparent instead of white
- activeOpacity previously not set is now 0.3
Resolves #2027

feat(Icon): Use platform Touchable

---

.travis.yml

When having both next and master, changes on master would then override the new additions made on next.

ci: Only deploy website changes from next

---

docs/image.md
src/avatar/Avatar.js
src/avatar/__tests__/__snapshots__/Avatar.js.snap
src/image/Image.js
src/image/__tests__/Image.js
src/image/__tests__/__snapshots__/Image.js.snap
src/index.d.ts
src/tile/__tests__/__snapshots__/Tile.js.snap

New `transition` prop that can be used to disable the fade transition on the Image component and surrounding components - Avatar, ListItem, Tile.
Resolves #2004
To use from Avatar, simply use the `imageProps` prop. e.g.
```jsx
<Avatar imageProps={{ transition: false }} />
```

feat(Image): Add transition prop

---

docs/icon.md
src/helpers/getIconType.js
src/icons/Icon.js
src/icons/__tests__/__snapshots__/Icon.js.snap
src/index.d.ts
src/pricing/__tests__/__snapshots__/PricingCard.js.snap
src/searchbar/__tests__/__snapshots__/SearchBar.js.snap

Allows using `font-awesome-5` anywhere icons are used. Also supports the brands, regular, and solid styles.
Resolves #1877 #1338

feat(Icon): Add support for FontAwesome5

---

docs/overlay.md
src/index.d.ts
src/overlay/Overlay.js
src/overlay/__tests__/Overlay.js
src/overlay/__tests__/__snapshots__/Overlay.js.snap

BREAKING CHANGE: Removes containerStyle, windowBackgroundColor, overlayBackgroundColor, borderRadius, width, and height props. Initial width and height of overlay are now `auto` before having set values.
- `containerStyle` is now `backdropStyle`
- `windowBackgroundColor`, can just set backgroundColor on `backdropStyle`
- `overlayBackgroundColor`, can just set backgroundColor on `overlayStyle`
- `borderRadius`, can just set borderRadius on `overlayStyle`
- `width` , `height`, can just set width and height on `overlayStyle`

refactor: Cleanup Overlay

---

package.json

Remove skipped tests from node_modules.
```
getTooltipCoordinate.js |       90 |    42.11 |      100 |    89.47 |    15,122,123,134 |
--------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 27 passed, 27 total
Tests:       284 passed, 284 total
Snapshots:   196 passed, 196 total
Time:        21.469s
Ran all test suites.
✨  Done in 22.92s.
```
Close #2154

fix(test): Exclude node_modules when running Jest #devcjog25

---

src/index.d.ts

when I use withTheme
```js
import React from 'react'
import {ThemeProps, withTheme } from 'react-native-elements'
interface Props extends ThemeProps<any>{
onPress: () => void
}
class Button extends React.Component {
// ... rest of all
}
const ThemeButton = withTheme(Button)
```
```js
<ThemeButton 
onPress={this.onPress}
/>
```
keep showing error about not providing required props `theme` `updateTheme` `replaceTheme`

fixed unnecessary ThemProps in withTheme hoc

---

package.json

Since Jest ignores `searchbar/__tests__/common.js` [#L74](https://github.com/react-native-elements/react-native-elements/blob/64315d6469cc34b67393e8c192d581118ed341c0/package.json#L74) we also need to ignore coverage for it as well.

fix(test): Add coveragePathIgnorePatterns property

---

src/tooltip/__tests__/Tooltip.android.js
src/tooltip/__tests__/Tooltip.js
src/tooltip/__tests__/__snapshots__/Tooltip.js.snap

```
tooltip                  |    91.14 |    48.89 |     87.5 |    90.91 |                   |
Tooltip.js              |    91.43 |    54.17 |    78.57 |    91.43 |         29,45,161 |
Triangle.js             |      100 |       50 |      100 |      100 |                12 |
getTooltipCoordinate.js |       90 |    42.11 |      100 |    89.47 |    15,122,123,134 |
```
```
tooltip                  |     96.2 |    75.56 |    91.67 |     96.1 |                   |
Tooltip.js              |    97.14 |    79.17 |    85.71 |    97.14 |               161 |
Triangle.js             |      100 |      100 |      100 |      100 |                   |
getTooltipCoordinate.js |       95 |    68.42 |      100 |    94.74 |            15,134 |
```

test: Increase code coverage for Tooltip component

---

.travis.yml

In `yarn`, we don't need the `run`.

chore: Remove redundant syntaxes

---

src/buttons/ButtonGroup.js
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
src/list/ListItem.js

RN styles parser allows `marginLeft` and `marginRight` to override `marginHorizontal` but not vice versa.
rel #2170

allow `marginHorizontal` and `marginVertical`  for ButtonGroup

---

docs/divider.md

I copy/pasted this example and it produced an error because of the trailing semi-colon. It was saying `Invariant Violation: Text strings must be rendered within a <Text> component` because it semi-colon is text. Took me a while to figure out what was going on there.

Remove trailing semi-colon

---

src/tooltip/getTooltipCoordinate.js

Fixes a minor typo in the comment of the file
coordincates -> coordinates

typo: getTooltipCoordinate

---

.github/FUNDING.yml

Leverage the GitHub sponsor button to make people aware about the various ways in which one can support the development.

meta: Added GitHub sponsor button config

---

src/checkbox/CheckBox.js

Allows the default `testID` prop value to be overwritten when such prop is provided.

fix(CheckBox): Allow default checkbox testID to be overwritten

---

docs/social_icons.md
src/social/SocialIcon.js
src/social/__tests__/__snapshots__/SocialIcon.js.snap

Fixes #872.
Adds a new prop `iconType` to the SocialIcon component.
```
<SocialIcon
title='Sign In With Facebook'
button
type='linkedin'
/>
<SocialIcon
title='Sign In With Facebook'
button
type='linkedin'
iconType='feather'
/>
```

fix: add iconType to SocialIcon

---

docs/avatar.md
src/avatar/Avatar.js
src/avatar/__tests__/Avatar.js
src/avatar/__tests__/__snapshots__/Avatar.js.snap
src/index.d.ts

Fixes: #1952
Changed the `editButton` fields to use `accessoryButton` instead. Added the option to use an Image source as the accessory button.
```js
<Avatar
large
rounded
source={l.image_url ? { uri: l.image_url } : null}
icon={l.icon}
title={l.title}
key={`${chunkIndex}-${i}`}
accessoryButton={{source: { uri: "https://homepages.cae.wisc.edu/~ece533/images/baboon.png"}}}
showAccessoryButton
/>
```

feat: image source for avatar accessory

---

src/checkbox/CheckBox.js
src/checkbox/__tests__/__snapshots__/CheckBox.js.snap

Fixes: #2305
When title was empty string it failed the `React.isValidElement` check correctly, but is falsey in the second statement leaving a string outside of any wrapping component.

fix empty string checkbox title crash

---

src/card/Card.js
src/card/__tests__/__snapshots__/Card.js.snap

Fixes #2336, As StyleSheet.flatten was not used array was getting created instead of object

Fix: Object getting created with key `0`

---

src/tooltip/Tooltip.js

Fixes: #2125 
I tried to find out why RN was not switching RTL 'left' and 'right' automatically as they should be. I think this is most likely a bug in react-native. But alas, it is what it is I suppose. Here is a simplified fix for this issue.

add rtl fix for tooltip modal content

---

src/searchbar/SearchBar-android.js
src/searchbar/SearchBar-default.js
src/searchbar/SearchBar-ios.js

`onFocus` and `onBlur` from react native return `event`, but we don't pass `event` to `this.props.onFocus` and `this.props.onBlur`.
The not passing event causes some problems when I need to get event from `onFocus` and `onBlur`.
Reference:
* onFocus: https://github.com/facebook/react-native/blob/bf0539fb51aa7dd0f9ad2b6587a047379e43fbe4/Libraries/Components/TextInput/TextInput.js#L1033
* onBlur: https://github.com/facebook/react-native/blob/bf0539fb51aa7dd0f9ad2b6587a047379e43fbe4/Libraries/Components/TextInput/TextInput.js#L1040

fix: Pass event in SearchBar

---

package.json
src/avatar/Avatar.js
src/badge/Badge.js
src/buttons/Button.js
src/buttons/ButtonGroup.js
src/card/Card.js
src/checkbox/CheckBox.js
src/config/ViewPropTypes.js
src/config/index.js
src/divider/Divider.js
src/header/Header.js
src/icons/Icon.js
src/image/Image.js
src/input/Input.js
src/list/ListItem.js
src/overlay/Overlay.js
src/pricing/PricingCard.js
src/searchbar/SearchBar-android.js
src/searchbar/SearchBar-default.js
src/searchbar/SearchBar-ios.js
src/slider/Slider.js
src/social/SocialIcon.js
src/text/Text.js
src/tile/FeaturedTile.js
src/tile/Tile.js
src/tooltip/Tooltip.js
src/tooltip/Triangle.js
yarn.lock

Fixes: #2257 
Also depends on a fixed version of RN-ratings: https://github.com/Monte9/react-native-ratings/pull/91
@Monte9

fix: remove React.PropTypes since deprecated

---

docs/pricing.md
src/pricing/PricingCard.js
src/pricing/__tests__/PricingCard.js
src/pricing/__tests__/__snapshots__/PricingCard.js.snap

Fixes: #2290
Changed pricing button so that it can accept all Button props. I also discovered that it would be possible for a developer to make a light themed button with a dark icon. So I improved the `button.icon` prop so that it can accept a string (and maintains old format), an object of Icon props, or a custom Icon.
Looking forward I think we could potentially deprecate the `onButtonPress` prop since it can be passed directly through button props instead.

improve PricingCard button props

---

.prettierrc

when running '`yarn lint`' on Windows, I keep getting Delete 'cr' [prettier/prettier](got error at every line of RNE), It's really annoying because I can't examine other changed files. Until a new attribute added to .prettierrc

Fix keep getting Delete 'CR' [prettier/prettier]

---

package.json
yarn.lock

I assumed that all `@types` packages should be installed as dev dependencies.

move @types/react-native-vector-icons to dev deps

---

src/avatar/Avatar.js
src/avatar/__tests__/__snapshots__/Avatar.js.snap

The rounded prop doesn't work in some cases. I've fixed it by injecting a borderRadius prop to the Image component.

fixes Avatar when rounded is true

---

src/searchbar/SearchBar-ios.js

I discovered a bug when using the iOS SearchBar where if the `showCancel` prop was set to `true`, then my keyboard was mysteriously reappearing and re-dismissing after navigating away from the screen with the search bar focused. After looking into it further, I found the culprit! It looks like when the `showCancel` prop was added to the SearchBar, the `setState` call in `onBlur` to set `hasFocus` to false was put behind a check to only set state when `showCancel` is falsy; however, the LayoutAnimation trigger that is meant to be coupled with the state update was left outside that conditional. This PR puts the LayoutAnimation trigger under the same conditional as setting state so that unexpected animations do not occur.

Stop triggering LayoutAnimation without setting state in SearchBar-ios

---

src/index.d.ts

This change will let users specify an `underlayColor` while using an icon in their `Header`. As an example, when faced with a problem like in https://github.com/react-native-elements/react-native-elements/issues/640 we can either use an `Icon` component and pass it the `underlayColor` prop or add the `underlayColor` to the `rightComponent` `HeaderIcon` type. However, the latter is not currently supported by the type definitions.

Have `IconObject` extend `TouchableHighlightProps` so that `HeaderIcon` can support props like `underlayColor`

---

src/tooltip/Tooltip.js

Removing is iOS check to fix onClose not firing in RN 0.63

Fixing RN 0.63 issue where iOS onClose does not fire

---

README.md

Link to docs for the Bottom Sheet component isn't included in the README.md file

Add missing link to Bottom Sheet component

---

website/docs/contributing.md
website/docusaurus.config.js
website/src/pages/help.js
website/versioned_docs/version-1.0.0/contributing.md
website/versioned_docs/version-1.1.0/contributing.md
website/versioned_docs/version-1.2.0/contributing.md
website/versioned_docs/version-2.0.4/contributing.md
website/versioned_docs/version-2.1/contributing.md

There are different names for GitHub (`Github` and `GitHub`).
I unified the name to the correct one - `GitHub`.

Rename Github to GitHub

---

src/tooltip/Tooltip.js

Rather than waiting an arbitrary time (500ms), let's wait for the screen to finish being painted, using requestAnimationFrame() #2237

Fix for slower Android devices calculating height

---

src/avatar/Avatar.js
src/list/ListItem.js
src/list/ListItemButtonGroup.js
src/list/ListItemCheckBox.js
src/list/ListItemChevron.js
src/list/ListItemContent.js
src/list/ListItemInput.js
src/list/ListItemSubtitle.js
src/list/ListItemTitle.js
src/list/__tests__/__snapshots__/ListItem.js.snap
website/blog/2020-08-10-2.3-upgrade-guide.md
website/docs/avatar.md
website/docs/badge.md
website/docs/listitem.md

Fixes: #2459
Remove `ListItem` sub-components, deprecate props.
Also deprecates `Avatar` accessory props.
TODO: 
1. double check that example continues to work
2. write blog post detailing upgrade details

deprecate ListItem subcomponents and avatar.accessory

---

src/image/Image.js
src/index.d.ts
website/docs/image.md

This Pull Request tries to solve the issue [816](https://github.com/react-native-elements/react-native-elements/issues/814) by following the instructions given by @flyingcircle in this [comment](https://github.com/react-native-elements/react-native-elements/issues/814#issuecomment-637161288), 
- I have added `onPress` and `onLongPress` props to `<Image />` component.
- I have also made sure that `<Component>` inside the `<Image />` component is set based on whether the user has passed either the `onPress` or `onLongPress` props or not. For inspiration, I have followed the `<Avatar />` component.
- By doing the aforementioned changes, we can make use of `imageProps` prop in `<Card />` component to pass `onPress` or `onLongPress` function props.
- Added  appropriate types in the …

FIX - 814 - Clickable image on the cards 

---

website/docs/badge.md
website/docs/bottomsheet.md
website/docs/button.md
website/docs/input.md
website/src/pages/index.js
website/static/css/components.css
website/versioned_docs/version-2.2.1/badge.md
website/versioned_docs/version-2.2.1/bottomsheet.md
website/versioned_docs/version-2.2.1/button.md
website/versioned_docs/version-2.2.1/input.md

The new docusaurus introduced some changes that broke the layout for component previews.
This commit just aligns them again.
Quick before and after:

docs(website): Fix component preview layout

---

src/image/Image.js

Fixes: #2417
At least for `styled-components` this should be enough for fixing the `style` prop itself. However, considering other style props that get passed on, it should be considered that before unpacking, flattening the input so that it can be consistently unpacked.

fix styled-components with Image comp

---

src/icons/Icon.js

fixed Icon issue, it has the wrong assignment of `reverseColor`.
whenever user try to use icon it shows can't access reverseColor before initialization error, it should be `reverseColorProp`, as `reverseColor` is destructured as `reverseColorProp`
current issue:
```
const { ...., reverseColor: reverseColorProp , ....} = props ;
const reverseColor = reverseColor || theme.colors.white;
```
issue fixed in pull request:
```
const { ... , reverseColor: reverseColorProp , ... } = props ;
const reverseColor = reverseColorProp || theme.colors.white;
```

Cannot access 'reverseColor' before initialization issue fixed.

---

src/list/ListItem.js

As of 2.3.0 when supplying a React element to a `ListItem`s `title` prop a `title.trim is not a function` error is thrown. This PR fixes the error and allows the console warning to be shown.

fix(ListItem): Avoid error when title is a React element

---

src/image/Image.js

fix(Image): Show placeholder when source prop exists but empty.

---

website/docs/button_group.md

This change fixes the incorrect `ButtonGroup` Component prop description, copying from the `Button` component.

Update Component default value in ButtonGroup

---

src/card/Card.js
src/card/CardTitle.js
src/card/__tests__/__snapshots__/Card.js.snap
src/image/__tests__/__snapshots__/Image.js.snap

move styles back to base Card

---

src/buttons/Button.js
src/buttons/__tests__/__snapshots__/Button.js.snap
website/docs/button.md

Closes #2493 
If the button has linear-gradient prop then it will render `TouchableOpacity` in Android instead of `TouchableNativeFeedback` in order to provide the user with feedback.
Not using `Pressable` because of the following reasons:
- Very New.
- Needs `@latest` version of React Native, therefore won't be possible for all users to upgrade RN.
- As mentioned above, that it's very new so API may change in future to make it more stable.

fix(Button): Improved UX of the LinearGradient button

---

website/docs/header.md
website/docs/icon.md

Rearranged the props section and reference section of documentation of header and icon in an alphabetical order.
Update for #2604

Docs: Arrange props and references alphabetically

---

package.json
yarn.lock

The new patched version:
- uses `useNativeDriver` for animation
- adds `tintColor` prop for RatingProps

Update react-native-ratings to latest

---

website/docs/avatar.md

**Improving the Documentation**
While working with `react-native-elements` Avatar components, I came across with problem of using Avatar child component Accessory. After my researches  I found version 2.3 Upgrade Guide where it was stated that props namely `accessory`, `showAccessory`, and `accessoryProps` are depreciated. However, I noticed that in documentation depreciated props were not removed. That's why I decided to remove depreciated props.

Avatar deprecated props removed from docs

---

src/avatar/Avatar.js
src/avatar/__tests__/Avatar.js
src/avatar/__tests__/__snapshots__/Avatar.js.snap

https://github.com/react-native-elements/react-native-elements/issues/2592
Fixed issue by adding a condition if `source.uri` doesn't exists
Added test for coverage

avatar not showing placeholder if not source

---

src/bottomSheet/BottomSheet.js
src/bottomSheet/__tests__/BottomSheet.js
src/bottomSheet/__tests__/__snapshots__/BottomSheet.js.snap
src/index.d.ts
website/docs/bottomsheet.md

The bottom sheet has an underlay that currently cannot be customized. This adds the containerStyle prop that is present in other components so that style customization on the underlay is possible.

Add bottom sheet containerStyle prop

---

src/config/ThemeProvider.js
src/config/__tests__/ThemeProvider.js

Fixes https://github.com/react-native-elements/react-native-elements/issues/2647.
Changelog:

fix(ThemeProvider): Custom theme lost on dark mode switch

---

package.json
src/config/index.js
src/header/Header.js
src/header/__tests__/__snapshots__/Header.js.snap
yarn.lock

Fixes: #2704 and #1791
`Header` still needs to be outside of the `SafeAreaView`, but this integrates `SafeAreaView` into the component itself so that the left and right components have better placement in landscape orientation.

update header component to handle more phone shapes/sizes

---

src/index.d.ts
website/versioned_docs/version-3.0.0/social_icons.md

Removed stack-overflow type from list since it doesnt exists in TypeScript type (SocialMediaType)
Supported types: 
export type SocialMediaType =
| 'facebook'
| 'twitter'
| 'google-plus-official'
| 'google'
| 'pinterest'
| 'linkedin'
| 'youtube'
| 'vimeo'
| 'tumblr'
| 'instagram'
| 'quora'
| 'flickr'
| 'foursquare'
| 'wordpress'
| 'stumbleupon'
| 'github'
| 'github-alt'
| 'twitch'
| 'medium'
| 'soundcloud'
| 'gitlab'
| 'angellist'
| 'codepen'
| 'weibo'
| 'vk';

add stack-overflow icon to prop type

---

src/bottomSheet/__tests__/BottomSheet.js
src/checkbox/CheckBoxIcon.js
src/helpers/getIconType.js

Fixes:  #2006
@zivchen if you are available, it'd be great if you could confirm if this fixes the issue.

dynamically import all font files

---

src/buttons/Button.js
src/header/Header.js
src/list/ListItem.js
src/list/__tests__/ListItem.js

Remove usage of global.Expo due to deprecation in SDK 40 and removal in SDK 41.
Fix #2747

Expo: remove global usage due to removal in SDK 41.

---

package.json
website/docs/getting_started.md

Having multiple versions of the react-native-safe-area-context causes an invariant violation when starting your app.  This fixes these two issues https://github.com/react-native-elements/react-native-elements/issues/2721 and https://github.com/react-native-elements/react-native-elements/issues/2768
I removed react-native-safe-area-context from dependencies and added it to peer and dev depencies.

change react-native-safe-area-context to a peer

---

src/avatar/Accessory.tsx

When Accessory was moved out of Avatar having a custom image as Avatar stopped working. See the issue [#2787](https://github.com/react-native-elements/react-native-elements/issues/2787)

Source prop missing in Image from Accessory.jsx

---

.github/CONTRIBUTING.MD

Update docs.
Fix outdated link.

docs: fix link for react-native-elements-app repository

---

src/index.ts

Exported AvatarProps from index.ts to allow importing AvatarProps from `react-native-elements` instead of `react-native-elements/dist/avatar/Avatar`

Exported AvatarProps for the issue #2802

---

src/slider/Slider.tsx

Fixed issue #2728 .
The slider component can now be used in expo-web. Earlier the slider can't move in expo web due to onMoveShouldSetPanResponder method.

Fixed Slider compatibility for expo web

---

src/tooltip/Tooltip.tsx

Fixes  issue #2751 
No
No
**Summary**
Added _isMounted in tooltip.tsx, set it true on componentDidMount and false on componentWillUnmount. Then added condition on setState so that it works only when the component is mounted
No

fix: Make sure component is mounted before calling setState. #2751

---

src/social/SocialIcon.tsx
website/docs/props/social_icons.md

Two new social icons added to SocialIcons component: facebook-messenger and WhatsApp.

add new social icons:facebook-messenger and whatsapp

---

src/tooltip/Tooltip.tsx

fix: onClose() is executed twice when tooltip is dismissed

---

src/index.ts
src/linearProgress/LinearProgress.tsx
src/linearProgress/__tests__/LinearProgress.js
src/linearProgress/__tests__/__snapshots__/LinearProgress.js.snap
src/linearProgress/index.ts
src/tooltip/Tooltip.tsx

New Component ```LinearProgress``` 
According to material desgin guidelines https://material.io/components/progress-indicators#linear-progress-indicators
Yupp
**Summary**
Nope

Added New component: LinearProgress

---

website/docs/props/avatar.md
website/docs/props/badge.md
website/docs/props/button_group.md
website/docs/props/checkbox.md
website/docs/props/icon.md
website/docs/props/listitem.md
website/docs/props/social_icons.md

Bugfix
**Summary**
In Docs, many of the props markdown files had broke internal link.
They were written in a bad markdown implicit id syntax ('uppercase characters not allowed').

docs links fixes

---

src/badge/Badge.tsx
src/buttons/Button.tsx
src/buttons/ButtonGroup.tsx
src/buttons/FAB.tsx
src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
src/checkbox/CheckBox.tsx
src/config/ThemeProvider.tsx
src/config/withTheme.tsx
src/divider/Divider.tsx
src/icons/Icon.tsx
src/input/Input.tsx
src/linearProgress/LinearProgress.tsx
src/pricing/PricingCard.tsx
src/searchbar/SearchBar-android.tsx
src/searchbar/SearchBar-default.tsx
src/social/SocialIcon.tsx
src/tile/FeaturedTile.tsx
src/tile/Tile.tsx

Strict TypeScript #2929

---

.github/workflows/build-and-deploy-to-dist.yml
website/docs/getting_started.md

Closes #2942 
Deployed branch -> https://github.com/pranshuchittora/react-native-elements/tree/dist

Build and deploy to dist via GitHub CI

---

src/avatar/__tests__/__snapshots__/Avatar.js.snap
src/image/Image.tsx
src/image/__tests__/Image.js
src/image/__tests__/__snapshots__/Image.js.snap
src/tile/__tests__/__snapshots__/Tile.js.snap
website/docs/props/image.md

I solve the problem of opened issue #2581. There are no breaking changes of project and even of component 😄 
Just I've added an extra style property for ```Image``` to avoid collision between children and image styles.
Btw, I didn't expect to see an extra wrapper for children (it's redundant from my perspective) but anyway I solve the problem based on already existing functionality and expectations of constant users.
I've extended one test case to ensure props pass correctly.
Yep.

bugfix: extra style prop for image children container

---

src/avatar/__tests__/__snapshots__/Avatar.js.snap
src/image/Image.tsx
src/image/__tests__/Image.js
src/image/__tests__/__snapshots__/Image.js.snap
src/tile/__tests__/__snapshots__/Tile.js.snap

Fixed #2992 
Added test when not using `childrenContainerStyle` props.
Snapshot was updated in https://github.com/react-native-elements/react-native-elements/pull/2933 , but when I didn't use `childrenContainerStyle` props, I returned Snapshot to same result as `3.3.2`.
No update required.
**Summary**
I wrote the reason in #2992 .
I thought I would use `childrenContainerStyle` instead of `style` for `View` component style only when `childrenContainerStyle` props was specified.
If `3.4.0` behaves correctly and I think it's a bug, please close this pull request.
（If you make a mistake in using `childrenContainerStyle` props, it would be helpful if you …

Fixed incompatible changes in Image component.

---

src/linearProgress/LinearProgress.tsx
src/linearProgress/__tests__/LinearProgress.tsx
src/linearProgress/__tests__/__snapshots__/LinearProgress.tsx.snap
src/slider/Slider.tsx
src/slider/__tests__/Slider.tsx
src/slider/__tests__/__snapshots__/Slider.tsx.snap
src/switch/__tests__/Switch.tsx
src/switch/__tests__/__snapshots__/Switch.tsx.snap
src/switch/switch.tsx
src/tab/__tests__/__snapshots__/tab.tsx.snap
src/tab/__tests__/tab.tsx
src/tab/tab.tsx

I noticed that LinearProgress had 0 accessibility props set. I added all relevant props for indicating progress to VoiceOver/TalkBack
No
No
**Summary**
Tested by setting these props directly in my app against existing LinearProgress component.
No

Add accessibility props + test to LinearProgress, Tab, Switch & Slider

---

src/BottomSheet/BottomSheet.tsx
src/BottomSheet/__tests__/BottomSheet.tsx
website/docs/main/props/bottomsheet.md

Add scrollViewProps to BottomSheet Component
Yes
Yes
**Summary**
I am using a library where if it's placed inside a ScrollView, the ScrollView's keyboardShouldPersistTaps props should be set to 'handled'
Close #3110
No

[BottomSheet] Add scrollViewProps to BottomSheet Component

---

src/ButtonGroup/ButtonGroup.tsx

Refactoring.
No, simple.
**Summary**
Addresses #522 and #672 where there is no way to tell if a button is selected when passing through a custom component to ButtonGroup.buttons.
Should not break.

Pass-through isSelected indicator to ButtonGroup

---

package.json
src/ButtonGroup/__tests__/__snapshots__/ButtonGroup.tsx.snap

[Fix] Latest merge issues

---

src/SocialIcon/SocialIcon.tsx

What kind of change does this PR introduce?
Fixes issue #3066  and  #3065
Did you add tests for your changes?
Not needed.
If relevant, did you update the documentation?
Not relevant.
Summary
This PR fixes issues #3066 and #3065. The SocialIcon was set to change the iconSize of only the inner symbol, not the whole component when raised was set to true. Now, it would change the size of the whole component by default according to the size mentioned in the iconSize prop, irrespective of the raised prop value. These changes also solve #3065.
Does this PR introduce a breaking change?
No
@khushal87 @flyingcircle @arpitBhalla @kyler-hyuna

Fix: Issue #3066 SocialIcon: Overall icon size doesn't change when prop raised={true}

---

src/Avatar/Avatar.tsx
src/Badge/Badge.tsx
src/Icon/Icon.tsx
src/Image/Image.tsx
src/LinearProgress/LinearProgress.tsx
src/LinearProgress/__tests__/LinearProgress.test.tsx
src/SocialIcon/SocialIcon.tsx
website/docs/main/Avatar.md
website/docs/main/Badge.md
website/docs/main/Icon.md
website/docs/main/Image.md
website/docs/main/SocialIcon.md
website/scripts/docgen/docgenParser.ts

This PR fixed the pressable props issue in the autogeneration of docs and also fixes the multiple exports from the LinearProgress component such that the `yarn docs:builds` runs successfully and the docs are updated automatically.
Reference - #3263

Fix issues with introduction of Pressable props in docs autogen

---

src/TabView/TabView.tsx

TabView Components Rotate
- When device rotation changes the tabview's item component width does not match the device dimensions.
- Within, there needed to change from old `Dimensions` class to the `useWindowDimensions`.
No, it did not need them.
No, it is not relevant.
No, it does not.
@khushal87 @flyingcircle @arpitBhalla @kyler-hyuna

Fix Rotate Bug Tabview

---

README.md

TabView isn't a header under the Tab page anymore. There is a separate page for the TabView component.  I fixed the broken link with this commit.

Fix the link of TabView component

---

example/src/views/lists/content.tsx

Centered button title alignment.
.

Fix#3301 Button title alignment

---

example/src/views/avatars.tsx
example/src/views/tiles.tsx

fix #3318 
Here in the Tiles component the last image with text has a UI bug , the bottom text is getting cut out from the screen
this Pr fixes this and it looks appropraite now

fix(example): update broken views

---

website/versioned_docs/version-4.0.0-beta.0/main/Icon.md

The closing curly bracket was added to the url which then was invalid.
Fixed by adding a space.

docs(Icon): fix broken link

---

packages/base/src/Icon/Icon.tsx
packages/base/src/Icon/__tests__/Icon.test.tsx

Fixes #3375
It's simply a reordering of property assignment, so the hardcoded `testID` doesn't unintentionally overwrite a passed-in `testID` (this is how all other similar components work... `Icon` seemed to be the exception)

fix(Icon): preserve custom testID property
