react-native-elements/react-native-elements

Readme.MD
=> Fix typo: trailing * in README

Readme.MD, package.json, src/checkbox/CheckBox.js, src/config/fonts.js, src/containers/Card.js, src/form/FormInput.js, src/form/FormLabel.js, src/list/ListItem.js, src/pricing/PricingCard.js, src/social/SocialIcon.js
=> updated styling, replaced default font family

Readme.MD, src/list/ListItem.js
This will allow user to use static image as well as network images
=> allow for static image resource

Readme.MD
There's no need for it as it's now baked into the core
=> Remove rnpm references

Readme.MD, src/buttons/Button.js, src/config/colors.js
Perhaps you can add built-in support for 'disabled` buttons. Great work so far, by the way!
=> Support for disabled buttons

Readme.MD
typo in rightIcon description in listItem
=> typo in rightIcon description in listItem

Readme.MD
Great project - much needed 😄  💯 
Look forward to contributing something a little more substantial in the future.
=> Fix Typo in Readme

src/buttons/ButtonGroup.js
I guess that `borderStyle && borderStyle` was a typo :)
=> Fix typo (remove duplicated condition)

src/buttons/Button.js
`!large ...` conditional placement was ignoring fontSize and buttonStyles props
=> Fix: Button - Defaulting to small broke some props

Readme.MD, package.json, src/helpers/getIconType.js
Add the new MaterialCommuntyIcons type from `react-native-vector-icons` version 4
=> Material Community icons

Readme.MD, src/list/ListItem.js
=> ListItem title can be a View tag

src/list/ListItem.js
Support both right title and chevron
=> feat(ListItem): support both right title and chevron

Readme.MD, src/buttons/Button.js
=> Added disabledStyle prop to button

src/config/colors.js, src/form/FormValidationMessage.js
Adding a Form Validation component. This can be show below the FormInput
Like this:
<FormLabel>Name</FormLabel>
<FormInput ... />
<FormValidationMessage>Your name is required</FormValidationMessage>
Little preview:
Cheers
=> Adding a Form Validation component. This can be show below the FormInput

src/slider/Slider.js
This is a bug fix related to #159.
=> Fixed Slider's value is not initialized to 0

Readme.MD
Correct the the minor typo in README for Card component.
=> Fix image path typo in README

Readme.MD
specifically for placeholder, placeholderTextColor and onChangeText
=> added some entries to the Search Bar documentation regarding props

Readme.MD, src/index.js
FormValidationMessage was added to docs as usable, but didn't work at all.
=> Fix: FormValidationMessage not importing

Readme.MD, src/tile/FeaturedTile.js, src/tile/Tile.js
Everytime a new component is added/fixed I implement it myself to see if I can improve the API in any way/fix bugs. 
@binoy14 I have updated the Tile component to fix the issues that I faced while implementing it. Create this PR for you to review it before it's merged. 
- added missing `activeOpacity` for Tile component
- added `iconContainerStyle` and also center Icon by default
- updated README for two typo's in props
=> Fixing minor bugs in Tile component

Readme.MD
Syntax highlight not active on Readme.
=> Fix markdown syntax type

Readme.MD, src/list/ListItem.js
=> Allow number to be Title and Subtitle

Readme.MD, src/input/Search.js
- Updated docs for the clear icon
In regards to #182
=> Added clear icon in Search box

Readme.MD, src/grid/Col.js, src/grid/Grid.js, src/grid/Row.js
- When passing styles using StyleSheet.create the type of of number
and Object.assign cannot deal with numbers
- Change style prop to containerStyle  **This is a breaking change**
- Check if child exists when checking for type
In Reference to #209 and #210
=> Fix issues with Grid, Col and Row

README.md, src/list/ListItem.js
This addresses #260, giving the ability to have a text input component within the listitem component.
=> Add optional text input component for list item

README.md, src/list/ListItem.js
=> Add option to have a Switch for ListItem

src/containers/Card.js, src/list/ListItem.js
=> Fix Card titleStyle to use Text Proptype instead of View Proptype

src/containers/Card.js
Read issue #188 for context. 
Updated Card Component API:
1. pass in `title` prop to render `Card Title` (OPTIONAL) (renders regardless of whether image is present or not)
2. pass in `featuredTitle` prop to render title over the image (OPTIONAL) (only works if `image` prop is present)
3. pass in `featuredSubtitle` prop to render subtitle over the image (OPTIONAL) (only works if `image` prop is present)
4. renders all the children within the card component (OPTIONAL)
``` js
<Card
title='FEATURED CARD'
featuredTitle='REACT NATIVE'
featuredSubtitle='The idea with React Native Elements is more about component structure than actual design.'
image={{uri:'http://cdn2.greatfon.com/uploads/picture/453/132/132453/tropical-paradise-beach-coast-2406.jpg'}}>
<Button
icon={{name: 'code'}} …
```
=> added featuredTitle prop to Card component

README.md, src/avatar/Avatar.js
=> Fix for avatar name and type

src/text/Text.js
=> Use ES6 spread for rest of the props

.travis.yml, package.json, yarn.lock
Adding support for [codecov](https://codecov.io).
Please note the setup is not complete yet until someone creates an account in [codecov](https://codecov.io) and grant permissions for this project.
cc: @Monte9 @binoy14
=> Adding codecov

README.md
adding codecov % in readme
fixing build status button url from readme
=> fix travis-ci url and adding codecov button

src/avatar/Avatar.js
=> Avatar: uses default Icon type if none is given

docs/index.md
see #314
Updates the index.md file from the README.md file to fix broken links on the website corresponding to old readme anchors
=> DOCS: updates index from readme to fix links

README.md, docs/API/swipedeck.md, docs/index.md, src/index.js, src/swipedeck/SwipeDeck.js, src/swipedeck/__tests__/SwipeDeck.js, src/swipedeck/__tests__/__snapshots__/SwipeDeck.js.snap
This PR adds a **SwipeDeck** component used to build Tinder Cards style functionality. Check out [react-native-tinder-cards](https://github.com/Monte9/react-native-tinder-cards) for an implementation example of this. 
Also, this component was inspired by Stephen Grider's Udemy course called React Native: Advanced Concepts.
Check it out here: https://www.udemy.com/react-native-advanced/learn/v4/overview
Checklist:
=> [NEW FEATURE] SwipeDeck Component

docs/API/lists.md, src/list/ListItem.js, src/list/__tests__/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
Fixes #301 
// @Monte9 @binoy14
=> feat(ListItem): Allow a react component to be passed for icon

docs/API/buttons.md, src/buttons/Button.js
Break 15 tests, but fixes #328.
=> Add container view to button component to fix round button feedback

docs/API/lists.md, src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
=> Adds onPress to Right Icon on ListItem

docs/API/lists.md, src/buttons/Button.js, src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
This PR fixes https://github.com/react-native-training/react-native-elements/issues/381, I'm pushing this to master since I think it should be fixed ASAP.
=> Fix: Button ripple throws exception on iOS

docs/API/rating.md, src/rating/Rating.js, src/rating/__tests__/Rating.js, src/rating/__tests__/__snapshots__/Rating.js.snap
1. A `readonly` prop that disables user interactions
2. Ability to set an initial rating value
3. Speed up the rendering of rating images by using native drivers
4. Ability to set the number of decimal places for rating values
Closes #388 
Please feel free to let me know if any further changes are required. Thanks for reviewing my work :)
=> Enhancements to the Rating component

src/header/Header.js, src/header/__tests__/__snapshots__/Header.js.snap
This PR fixes https://github.com/react-native-training/react-native-elements/issues/427. Other modifications are because of prettier messing with my code :wink:
=> Fix header appearing at the bottom of the screen

src/list/List.js, src/list/ListItem.js, src/list/__tests__/__snapshots__/List.js.snap, src/list/__tests__/__snapshots__/ListItem.js.snap
Fixed #443 
Related [issue](https://github.com/facebook/react-native/issues/12401)
=> Fixed list item border bleeding

src/avatar/Avatar.js
Reverts react-native-training/react-native-elements#360
=> Revert "Create new Avatar component with configurable edit button and status indicator"

src/swipedeck/SwipeDeck.js
fixes https://github.com/react-native-training/react-native-elements/issues/418
=> adding zIndex, fix swipedeck elevation problem on android devices

src/social/SocialIcon.js
=> [SocialIcon] Fix boolean value for onLongPress

docs/API/icons.md
Making PR to confirm the wording
=> Added link to icons directory

docs/API/forms.md, example/src/views/forms_home.js, example/src/views/lists_home.js, src/form/FormInput.js, src/form/__tests__/__snapshots__/FormInput.js.snap
[ref](https://github.com/react-native-training/react-native-elements/issues/377)
This pr provides a new props to `FormInput` component: `shake`.
With it, you can do things like that (provide error interaction)
The prop `shake` is a comparable variable, it can be boolean, object, number, ... everything comparable with `===` comparaison. So, each time `shake` changed and is different than its previous value, it'll shake the input.
`const errorMessage = null;`
```jsx
<TextInput
shake={!errorMessage ? false : true}
...props
/>
```
If you have an error, for example
`const errorMessage = 'oh god, an error';`
`shake` will be true and it'll shake the input.
To re-shake the input, `shake` needs to be false and true again to trigger the shake.
If you want to shake the input each time an error …
=> FormInput shake animation

docs/API/divider.md
The title was mislabeled for the props.
=> Update "Badge props" to "Divider props"

docs/API/forms.md
Visible on https://react-native-training.github.io/react-native-elements/API/forms/
=> docs(forms): fix typo for a good looking website

docs/API/buttons.md, package-lock.json
#587 
I would like to set `containerViewStyle ` property to the first order of the list because it is an important property that easily overlook if it is set to the last property.
All the Best
=> #Improve from #587

src/buttons/Button.js
add condition for android version < 21 @iRoachie
=> fix for #597

package.json
=> chore(opencollective): Remove open collective postinstall

docs/API/buttons.md
=> Added button loading prop to the API doc

docs/API/lists.md, src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
Allows disabling of listItem and exposes disabledStyle prop for custom disabled style to listItem.
=> feat #355 Allow disable on list item

src/form/FormInput.js, src/form/__tests__/__snapshots__/FormInput.js.snap, src/input/Search.js, src/input/__tests__/__snapshots__/Search.js.snap
Addresses #665 to solve #331 again (regression occurred at some point).
=> Remove selectionColor to fix issue on android

src/avatar/Avatar.js, src/badge/badge.js, src/buttons/Button.js, src/buttons/ButtonGroup.js, src/card/Card.js, src/checkbox/CheckBox.js, src/form/FormInput.js, src/form/FormLabel.js, src/form/FormValidationMessage.js, src/header/Header.js, src/header/NavButton.js, src/header/Title.js, src/icons/Icon.js, src/input/Search.js, src/list/List.js, src/list/ListItem.js, src/pricing/PricingCard.js, src/social/SocialIcon.js, src/tile/FeaturedTile.js, src/tile/Tile.js
=> fix(*): Spread passed props first to prevent computed props rewrite

src/header/Header.js, src/header/__tests__/__snapshots__/Header.js.snap
- Header had strange behavior on rotation and it wasn't being rendered properly.
Fixes #701
=> Fix Header width on rotation

package.json, src/index.d.ts
As discussed @iRoachie, this brings the typescript definitions up to date with contributions in DefinitelyTyped
=> Pull in updates from DefinitelyTyped

example/src/drawer/home.js, example/src/drawer/playground.js, example/src/drawer/pricing.js, example/src/drawer/ratings.js
https://react-native-training.github.io/react-native-elements/API/icons/
=> Have Icon Use Correct iconStyle Props

src/index.d.ts
=> Added JSX.Element to ListItem avatar type definition

src/index.d.ts
=> Add disabled property to ListItem type definition

docs/API/searchbar.md, src/input/Search.js, src/input/__tests__/Search.js, src/input/__tests__/__snapshots__/Search.js.snap
#780 
**Code**
```jsx
<SearchBar icon={{ type: 'font-awesome', name: 'glass' }} />
```
**Result**
=> Custom icon searchbar

example/src/views/lists_home.js
Reverts react-native-training/react-native-elements#782
=> Revert "Adjusted Avatars Card and children Views"

package-lock.json, package.json, src/tile/FeaturedTile.js, src/tile/__tests__/__snapshots__/FeaturedTile.js.snap
resizeMode removed from stylesheet
Closes #740
=> Failed prop type/style fix

example/src/views/lists_home.js, src/list/ListItem.js
=> ListItem avatarStyle should be Image style

docs/API/buttons.md, example/src/views/lists_home.js
Adding documentation for rounded, outline and transparent added in https://github.com/react-native-training/react-native-elements/pull/382
=> Documentation for rounded, outline and transparent

src/tile/Tile.js, src/tile/__tests__/Tile.js, src/tile/__tests__/__snapshots__/Tile.js.snap
=> Pass activeOpacity to TouchableOpacity inside Tile

src/list/ListItem.js
"added a small enhancement for Listitem Icon" This includes the changes of the value in size for RightIcon so that it can take in rightIcon.size || 28. #812
=> rightIcon Size

src/slider/Slider.js, src/slider/__tests__/Slider.js, src/slider/__tests__/__snapshots__/Slider.js.snap
=> uses thumbStyle.transform values in the thumb View

README.md, docs/API/buttons.md, docs/API/input.md
Now I'm not submitting anything until this gets merged LOL 😂 
~~Oops noticed the `Button` component just changed, sending another commit~~
And its done 🎉 
@Monte9 You can review this one now
=> Button & Input docs

README.md, docs/API/buttons.md, docs/API/input.md, docs/API/overlay.md, docs/index.md, src/input/Input.js
* Button & Input docs
* Updated Button with new props
=> Button & Input docs (#864)

README.md
Seeks to clear up confusion about what todo items are available to start
=> docs(readme): Make README clearer about Todo items

website/siteConfig.js
And BOOM, search feature for the new documentations 🔥 💯
Thanks @s-pace for his help at algolia ! 🤝
=> Add algolia search

src/buttons/Button.js, src/pricing/__tests__/__snapshots__/PricingCard.js.snap
If you are in Expo, you don't have to specified ViewComponent props to use LinearGradient button
=> [Button] Auto import LinearGradient if Expo

docs/button.md, docs/tile.md, website/versioned_docs/version-0.19.0/button.md, website/versioned_docs/version-0.19.0/tile.md
=> Add touchable props Notice to Tile

src/buttons/Button.js, src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Ref https://github.com/react-native-training/react-native-elements/issues/893
=> Adds disabled and disabledStyle to Button

src/avatar/Avatar.js
Ref: https://github.com/react-native-training/react-native-elements/issues/942
Related PR in `react-native-elements-app`: https://github.com/react-native-training/react-native-elements-app/pull/46
=> Add support for different icon type in Avatar component #942

src/buttons/Button.js
I checked out a new branched and cherry picked only the needed commit. seems cleaner and has no conflicts too . #971 
Refs #959
=> Text default width

docs/contributing.md, docs/icon.md, docs/slider.md, docs/testing.md, docs/tile.md, website/versioned_docs/version-0.19.0/contributing.md, website/versioned_docs/version-0.19.0/icon.md, website/versioned_docs/version-0.19.0/slider.md, website/versioned_docs/version-0.19.0/testing.md, website/versioned_docs/version-1.0.0-beta3/contributing.md
I just want to improve the document. During working on this, I have used https://languagetool.org/ to automatically check the typos and grammar issues.
Please let me know if there's any change you think unsuitable.
=> Improve grammar and fix typos for some documents

src/buttons/ButtonGroup.js, src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
=> fix(ButtonGroup): Set style background color to ButtonGroup

.ci/expo-ci.sh, .ci/index.js, .ci/package.json
Update the CI script to make the bot modify its comment instead of adding a new one
=> CI: The bot now modifies its own comment

.gitignore, website/versioned_docs/version-0.19.0/avatar.md, website/versioned_docs/version-0.19.0/badge.md, website/versioned_docs/version-0.19.0/button.md, website/versioned_docs/version-0.19.0/button_group.md, website/versioned_docs/version-0.19.0/card.md, website/versioned_docs/version-0.19.0/checkbox.md, website/versioned_docs/version-0.19.0/divider.md, website/versioned_docs/version-0.19.0/forms.md, website/versioned_docs/version-0.19.0/header.md, website/versioned_docs/version-0.19.0/icon.md, website/versioned_docs/version-0.19.0/lists.md, website/versioned_docs/version-0.19.0/pricing.md, website/versioned_docs/version-0.19.0/rating.md, website/versioned_docs/version-0.19.0/searchbar.md, website/versioned_docs/version-0.19.0/slider.md, website/versioned_docs/version-0.19.0/social_icons.md, website/versioned_docs/version-0.19.0/text.md, website/versioned_docs/version-0.19.0/tile.md, website/versioned_docs/version-1.0.0-beta2/button.md, website/versioned_docs/version-1.0.0-beta2/button_group.md, website/versioned_docs/version-1.0.0-beta2/input.md, website/versioned_docs/version-1.0.0-beta2/overlay.md, website/versioned_docs/version-1.0.0-beta2/searchbar.md, website/versioned_docs/version-1.0.0-beta3/button.md, website/versioned_docs/version-1.0.0-beta3/card.md, website/versioned_docs/version-1.0.0-beta3/header.md, website/versioned_docs/version-1.0.0-beta3/searchbar.md
=> New website props layout

src/searchbar/SearchBar-default.js
=> set size of Icon or clearIcon in SearchBar

src/buttons/Button.js
=> fix(Title) Move disabled style

docs/listitem.md, website/versioned_docs/version-1.0.0-beta4/listitem.md
'checkbox' corrected to 'checkBox'
=> Fix typo in listitem.md

src/badge/badge.js
This is an implementation of #1058
=> Allowed Badge to accept any component as the Container component

src/buttons/ButtonGroup.js, src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap
=> Button group use platform touchable 

src/social/SocialIcon.js
Hi, I would like to add WeChat theme to the SocialIcon list as well.  
Color HEX was found via: https://brandcolors.net/b/wechat
Thanks!
=> Add WeChat color to SocialIcon

src/list/ListItem.js
ref: https://github.com/react-native-training/react-native-elements/issues/1081
=> Fix ListItem platform checkmark size

docs/overlay.md, src/index.d.ts, src/overlay/Overlay.js, src/overlay/__tests__/__snapshots__/Overlay.js.snap
=> Dismiss overlay by touching overlaybackground

.prettierrc, docs/troubleshooting.md, website/i18n/en.json, website/sidebars.json, website/versioned_docs/version-0.19.0/troubleshooting.md, website/versioned_sidebars/version-0.19.0-sidebars.json, website/versioned_sidebars/version-1.0.0-beta2-sidebars.json, website/versioned_sidebars/version-1.0.0-beta3-sidebars.json, website/versioned_sidebars/version-1.0.0-beta4-sidebars.json
=> docs(website): Add Troubleshooting section

docs/listitem.md, package-lock.json, src/index.d.ts, src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
=> (ListItem) Customize padding with pad prop

src/searchbar/SearchBar-default.js
handle `onPress` method of clearIcon on `SearchBar-default`
=> fix: onClear for default searchbar

src/buttons/Button.js
=> Fix Button Ripple on Android Version 21 and higher

.ci/setupTests.js, package.json, src/buttons/Button.js, src/buttons/__tests__/Button.js, src/buttons/__tests__/__snapshots__/Button.js.snap, src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap, src/overlay/__tests__/Overlay.js, src/overlay/__tests__/__snapshots__/Overlay.js.snap, src/pricing/__tests__/__snapshots__/PricingCard.js.snap, src/rating/__tests__/__snapshots__/Rating.js.snap, yarn.lock
Had to upgrade enzyme.
Added tests for `Button`
=> Add some tests 

src/searchbar/SearchBar-ios.js, src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
=> Fix iOS SearchBar

website/versioned_docs/version-1.0.0-beta5/avatar.md
I added icon type `type: 'font-awesome'` to each `Avatar` with icon
=> docs: `Avatar` with icon requires icon type

docs/avatar.md
Specify icon type
Without icon type, icon will return with `?`
=> docs: missing icon type for Avatar

docs/avatar.md, src/avatar/Avatar.js, src/index.d.ts
=> Custom ImageComponent for Avatar

website/versioned_docs/version-0.19.0/button.md
Typo in the documentation. Fixes future issues like #1290
=> docs(button): 0.19.0 component prop should be Component

src/buttons/Button.js
=> (Button) Remove borderRadius change from disabled style

src/tooltip/Tooltip.js
Add patch to Tooltip, @hegelstad pointed out a bug on this module inside scroll view, it wouldn't position itself correctly as you scroll down. This is the fix.
=> fix(tooltip): patch for positioning inside scroll view

src/checkbox/CheckBox.js, src/checkbox/__tests__/__snapshots__/CheckBox.js.snap, src/index.d.ts, website/versioned_docs/version-0.19.0/checkbox.md
Fix https://github.com/react-native-training/react-native-elements/issues/1339
=> Expose wrapperStyle prop on Checkbox

package.json
=> Accept 5.x of react-native-vector-icons

website/versioned_docs/version-0.19.0/button.md
=> docs(Button-0.19): Change fontSize type to number

docs/tile.md, website/versioned_docs/version-0.19.0/tile.md
Brought to my attention in https://github.com/react-native-training/react-native-elements/issues/199#issuecomment-417271146
=> docs(Tile 0.19): Fix imageSrc to use correct requires

website/versioned_docs/version-0.19.0/lists.md
since ListView is deprecated it is not working properly or giving errors in newer versions of RN
=> [docs] changed ListView ( deprecated ) to FlatList

src/list/ListItem.js, src/list/__tests__/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
Fixes #1343 
the defaultProps (e.g. titleProps, rightTitleProps ...etc) where completely ignored after refactoring.
This should fix the issue. Also I have updated the snapshot test to add some custom props
=> Fixes props being ignored on ListItem

src/index.d.ts
=> Add registerCustomIconType typing

package.json, src/index.d.ts, yarn.lock
=> fix(types): Button correctly extend touchable props

src/index.d.ts
Type definition for ListItem's component prop was incorrect
Closes #1465
=> fix(types): Correct type for ListItem component prop

src/index.d.ts
Current typings required that the theme object have in the colors
property
Closes #1467
=> fix(types): Allow partial theme be passed to ThemeProvider

docs/getting_started.md
Fixed develops -> developers in the following sentence.
There are many great ui components made by developers all around open source.
=> Small Typo Fix on Getting Started Page

website/versioned_docs/version-0.19.1/overview.md
Purpose: to encourage developers to experiment with the components in the library
=> Added a small call to action

docs/overview.md
Added a small call to action to encourage developers to experiment with the components in the library.
=> Made small updates to the prose at the top

docs/tile.md
Added import statements for Tile
=> Added import statements for Tile

docs/divider.md
Included import statement for Divider.
=> Included an import statement

docs/avatar.md
Some of the code snippets on this page did not have import statements so I added some.
=> Included import statements for code snippets

src/avatar/Avatar.js
=> Change PropTypes to object to avoid the warning

docs/button.md, website/versioned_docs/version-1.0.0-beta2/button.md, website/versioned_docs/version-1.0.0-beta3/button.md, website/versioned_docs/version-1.0.0-beta5/button.md
Clears up issues like https://github.com/react-native-training/react-native-elements/issues/1524
=> docs(website): Add linear gradient usage section to Button docs

docs/avatar.md, docs/badge.md, docs/button.md, docs/button_group.md, docs/card.md, docs/checkbox.md, docs/divider.md, docs/header.md, docs/icon.md, docs/input.md, docs/listitem.md, docs/overlay.md, docs/pricing.md, docs/rating.md, docs/searchbar.md, docs/slider.md, docs/social_icons.md, docs/text.md, docs/tile.md, docs/tooltip.md
=> docs(website): Add descriptions for every component

package.json, src/config/withTheme.js, yarn.lock
=> fix: Hoist statics for withTheme hoc

src/searchbar/SearchBar-android.js, src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
=> fix: Android SearchBar clear icon was using cancel icon

docs/button_group.md, docs/card.md, docs/checkbox.md, docs/divider.md, docs/header.md, docs/icon.md, docs/input.md, docs/listitem.md, docs/overlay.md, docs/pricing.md, docs/rating.md, docs/searchbar.md, docs/slider.md, docs/social_icons.md, docs/text.md, docs/tile.md, docs/tooltip.md, website/siteConfig.js, website/static/css/components.css, website/static/css/custom.css
Closes #1544
This PRs adds a side menu on the right, of the docs that a table of contents for headings.
=> docs(website): Add onPageNav layout for website

docs/button_group.md, src/buttons/ButtonGroup.js, src/buttons/__tests__/ButtonGroup.js, src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap, src/index.d.ts
BREAKING CHANGE: `disableSelected` prop has been removed
Closes #1326 
Adds props:
- disabled
- disabledStyle
- disabledSelectedStyle
- disabledTextStyle
- disabledSelectedTextStyle
=> feat(ButtonGroup): Add disabled styles

src/image/Image.js, src/image/__tests__/__snapshots__/Image.js.snap
=> fix(Avatar|Image): Fade out placeholder when image loads

src/buttons/__tests__/ButtonGroup.js, src/config/__tests__/ThemeProvider.js, src/header/Header.js, src/helpers/renderNode.js, src/list/ListItem.js, src/searchbar/SearchBar-android.js, src/searchbar/SearchBar-default.js, src/searchbar/SearchBar-ios.js, src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap, src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap, src/searchbar/__tests__/__snapshots__/SearchBar.js.snap, src/tooltip/Tooltip.js, src/tooltip/getTooltipCoordinate.js
Hello,
I fixed existing eslint errors (19 errors on `next` branch). Most of them are related to unused variables and missing props validation.
I suggest adding `npm lint` to husky pre-commit hook and Travis CI pipeline.
=> fix:  Remove eslint errors

src/input/Input.js, src/input/__tests__/__snapshots__/Input.js.snap, src/list/ListItem.js, src/list/__tests__/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap, src/searchbar/SearchBar-android.js, src/searchbar/SearchBar-default.js, src/searchbar/SearchBar-ios.js, src/searchbar/__tests__/__snapshots__/SearchBar-android.js.snap, src/searchbar/__tests__/__snapshots__/SearchBar-default.js.snap, src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap, src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Also updated other components that use Input so they'll have no visible
changes.
Closes #1640
=> fix(Input): Make width to be 100% instead of 90%

docs/overlay.md, src/config/withTheme.js, src/index.d.ts, src/overlay/Overlay.js, src/overlay/__tests__/Overlay.js, src/overlay/__tests__/__snapshots__/Overlay.js.snap, website/i18n/en.json
Fixes all the overlay bugs
Closes #1312, #1311, #1215, #1517
=> Overlay fixes

src/slider/Slider.js, src/slider/__tests__/Slider.js, src/slider/__tests__/__snapshots__/Slider.js.snap
=> Bound slider value between min and max

src/slider/Slider.js, src/slider/__tests__/__snapshots__/Slider.js.snap
=> Fix slider on android with LayoutAnimation

src/text/Text.js, src/text/__tests__/Text.js
=> feat(Text): Allow style prop to accept array of objects

src/index.d.ts, src/input/Input.js, src/input/__tests__/Input.js
Based on #1232  added setNativeProps(nativeProps) method to Input.
=> [Input] Direct Manipulation

package.json, website/pages/en/index.js, website/static/css/custom.css
=> Added Showcase section to website

src/card/__tests__/__snapshots__/Card.js.snap, src/divider/Divider.js, src/divider/__tests__/Divider.js, src/divider/__tests__/__snapshots__/Divider.js.snap, src/index.d.ts
=> feat(Divider): Allow passing view properties

docs/button.md, website/versioned_docs/version-1.0.0/button.md
fix missing comma typo in button docs
=> fix missing comma typo in button docs

src/text/Text.js
- added propType fontFamily in src/text/Text.js
- added defaultProp fontFamily in src/text/Text.js
=> ESLint error in Text.js Component

docs/labels.md, website/versioned_docs/version-0.19.1/labels.md
=> added cancelButtonTitle prop to index.d.ts

docs/checkbox.md, src/checkbox/CheckBox.js, src/checkbox/__tests__/CheckBox.js, src/checkbox/__tests__/__snapshots__/CheckBox.js.snap, src/index.d.ts
Allows passing Text props to the title
Implements #1273
=> feat(CheckBox): Add titleProps prop

website/pages/en/index.js
=> Add Le Cheese to Showcase

src/index.d.ts
=> fix: add cancel method type for search bar

website/blog/2019-01-27-1.0-release.md
...to achieve parity with pre-1.0 List component styles.
=> Add List styling instructions

src/slider/Slider.js
For Issue GH-1738
- changed style of mainStyles.thumbHorizontal, mainStylesthumbVertical to take height/width into consideration (respectively)
- passed props.trackStyle width/height if provided by user
=> Fixed false positioning of Slider Thumb

src/text/Text.js
=> fix(Text): Allow header styles to override bold styles

docs/tile.md, src/index.d.ts, src/tile/FeaturedTile.js, src/tile/Tile.js, src/tile/__tests__/FeaturedTile.js, src/tile/__tests__/Tile.js, src/tile/__tests__/__snapshots__/FeaturedTile.js.snap, src/tile/__tests__/__snapshots__/Tile.js.snap
Allow customizing additional props on the image component.
Implements #1850
=> feat(Tile): Add imageProps prop

src/searchbar/SearchBar-android.js, src/searchbar/SearchBar-default.js, src/searchbar/SearchBar-ios.js
=> feat(SearchBar): Allow default testID to be overridden

docs/searchbar.md, website/versioned_docs/version-1.0.0/searchbar.md
prop was removed in v1 but docs were never updated.
=> docs(SearchBar): Remove noIcon prop

src/index.d.ts
Hi! This PR is to fix #1897, hope this can be merged 😁
@iRoachie
=> fix #1897 , ImageSourcePropType

docs/social_icons.md, src/index.d.ts, src/social/SocialIcon.js
=> feat: Allow social icon type google

docs/tooltip.md, src/index.d.ts
* Fixed TooltipProps.toggleOnPress property
* Added toggleTooltip method to Tooltip
=> Updated type definitions

src/pricing/PricingCard.js
=> fix(PricingCard): Correct text style proptypes

docs/pricing.md, src/index.d.ts, src/pricing/PricingCard.js, src/pricing/__tests__/PricingCard.js, src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Adding title style to pricing table button
I add an issue here https://github.com/react-native-training/react-native-elements/issues/1905
=> Add title style to pricing table button

src/index.d.ts
=> fix(types): Allow ListItem to have TouchableHighlight props

src/checkbox/CheckBox.js, src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
=> feat: Add testID to checkbox

src/searchbar/SearchBar-ios.js, src/searchbar/__tests__/__snapshots__/SearchBar-ios.js.snap
=> fix(Searchbar-ios): Contain text within cancel animation

docs/header.md, src/header/Header.js, src/header/__tests__/Header.js, src/index.d.ts
|Simple Header|with ImageBackground|with linear-gradient|
|-|-|-|
|![image](https://user-images.githubusercontent.com/17120764/54864035-55f9ce80-4d83-11e9-99a7-56816fb5c79d.png)|![image](https://user-images.githubusercontent.com/17120764/54864042-74f86080-4d83-11e9-825c-09c9907effcb.png)|![image](https://user-images.githubusercontent.com/17120764/54864048-82154f80-4d83-11e9-8833-86fa1624fca1.png)|
Close #1569
=> feat: Support for linear-gradient in Header Component

docs/social_icons.md, src/index.d.ts, src/social/SocialIcon.js
Adds weibo, flickr, and vk.
Resolves #1563
=> feat(SocialIcon): Add new social networks

src/avatar/__tests__/__snapshots__/Avatar.js.snap, src/image/Image.js, src/image/__tests__/Image.js, src/image/__tests__/__snapshots__/Image.js.snap
Same layout now exist for iOS and Android allowing requests like #1953 #1835 possible.
=> refactor: Base Image on ImageBackground

src/avatar/__tests__/__snapshots__/Avatar.js.snap, src/image/Image.js, src/image/__tests__/__snapshots__/Image.js.snap
=> fix(Image):  Allows interacting with children after load

src/card/Card.js, src/card/__tests__/__snapshots__/Card.js.snap
=> feat: Update Card to use new Image Component

src/tile/Tile.js, src/tile/__tests__/__snapshots__/Tile.js.snap
=> feat(Tile): Use RNE Image component

docs/listitem.md
`<ListItem />` does not have a property called `chevronColor`. Instead you should change the chevron's color using `<Icon />` props.
=> Fix API example for LinearGradient

docs/searchbar.md, src/index.d.ts, src/searchbar/SearchBar-ios.js, src/searchbar/__tests__/__snapshots__/SearchBar.js.snap, website/i18n/en.json
Allows the cancel button of the search bar to remain visible after blur events.
Resolves #1303
=> feat(SearchBar-ios): Add showCancel prop

docs/web_usage.md, website/i18n/en.json, website/sidebars.json
=> docs: Add react-native-web usage

docs/customization.md, src/config/ThemeProvider.js, src/config/index.js, src/index.d.ts, src/index.js
=> feat: Export ThemeContext for usage with hooks

src/config/ThemeProvider.js
Bug introduced in https://github.com/react-native-training/react-native-elements/commit/49ca4d0f2d306d01d8e42d90bd57e2978d016d3c
=> fix: Regression with initial context value

src/avatar/__tests__/__snapshots__/Avatar.js.snap, src/card/__tests__/__snapshots__/Card.js.snap, src/image/Image.js, src/tile/__tests__/__snapshots__/Tile.js.snap
Using hooks is breaking change for users. My bad :\ Reverting to non-hooks usage.
Fixes #2076
=> fix: Revert Image to not use hooks

src/image/Image.js, src/image/__tests__/Image.js
Honors the Test Id if passed on the image component.
=> #2091 Honor testID if passed.

src/avatar/Avatar.js
This PR tries to fix the issue [Issue-2059](https://github.com/react-native-training/react-native-elements/issues/2059)
=> fix(Avatar): Unable to add border to avatar #2059

src/list/ListItem.js
=> fix(ListItem): Update PadView to work on web

.github/CONTRIBUTING.MD, .github/ISSUE_TEMPLATE/bug_report.md, .travis.yml, README.md, docs/contributing.md, docs/getting_started.md, docs/icon.md, docs/labels.md, docs/troubleshooting.md, package.json, website/README.md, website/blog/2019-01-27-1.0-release.md, website/core/Footer.js, website/pages/en/help.js, website/pages/en/versions.js, website/siteConfig.js, website/versioned_docs/version-0.19.1/contributing.md, website/versioned_docs/version-0.19.1/getting_started.md, website/versioned_docs/version-0.19.1/header.md, website/versioned_docs/version-0.19.1/icon.md, website/versioned_docs/version-0.19.1/labels.md, website/versioned_docs/version-0.19.1/troubleshooting.md, website/versioned_docs/version-1.0.0/contributing.md, website/versioned_docs/version-1.0.0/icon.md, website/versioned_docs/version-1.2.0/getting_started.md, website/versioned_docs/version-1.2.0/troubleshooting.md
Updates to docs that need to be made since we moved to org
=> New repo docs

src/index.d.ts
fixes typescript error for tile component
=> added overlayContainerStyle to index.d.ts

.github/CONTRIBUTING.MD, .github/ISSUE_TEMPLATE/bug_report.md, .travis.yml, README.md, docs/contributing.md, docs/getting_started.md, docs/icon.md, docs/labels.md, docs/troubleshooting.md, package.json, website/README.md, website/blog/2019-01-27-1.0-release.md, website/core/Footer.js, website/pages/en/help.js, website/pages/en/versions.js, website/siteConfig.js, website/versioned_docs/version-0.19.1/contributing.md, website/versioned_docs/version-0.19.1/getting_started.md, website/versioned_docs/version-0.19.1/header.md, website/versioned_docs/version-0.19.1/icon.md, website/versioned_docs/version-0.19.1/labels.md, website/versioned_docs/version-0.19.1/troubleshooting.md, website/versioned_docs/version-1.0.0/contributing.md, website/versioned_docs/version-1.0.0/icon.md, website/versioned_docs/version-1.2.0/getting_started.md, website/versioned_docs/version-1.2.0/troubleshooting.md
https://github.com/react-native-elements/react-native-elements/pull/2109 should've been made to `master` but instead was made to `next`
=> Updates master with changes of new repo

src/checkbox/CheckBox.js, src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
Adds roles and states for checkbox
=> feat(CheckBox): Improve accessibility

src/buttons/Button.js, src/buttons/__tests__/__snapshots__/Button.js.snap, src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Some nice improvements for button, mainly on android. Other non-visible changes are improvements to accessibility and a ripple fix for border-radius
The Ripple color now correctly matches the background and foreground text like it should.
**Solid (current)**
**Solid (after)**
**Clear (current)**
**Clear (after)**
=> Few fixes and Improvements for Button

src/buttons/Button.js, src/buttons/__tests__/__snapshots__/Button.js.snap, src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Reverts react-native-elements/react-native-elements#2137
=> Revert "Few fixes and Improvements for Button"

docs/overlay.md, docs/tooltip.md, docs/web_usage.md, src/index.d.ts, src/overlay/Overlay.js, src/tooltip/Tooltip.js
=> Overlay and Tooltip: add ModalComponent prop

src/buttons/Button.js, src/buttons/__tests__/Button.js
Implement for https://github.com/react-native-elements/react-native-elements/issues/2141
=> Check whether loading is false before call onPress

docs/input.md
I could not find the onChangeText handler in the documentation i had to look elsewhere, I hope you will update this :)
=> Update Onchangetext on input

docs/checkbox.md, src/checkbox/__tests__/CheckBox.js, src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
=> Add Component to Checkbox Title options

docs/listitem.md, website/versioned_docs/version-1.2.0/listitem.md
Adds message that ListItem receives all props from TouchableHighlight. Fixes [#2174](https://github.com/react-native-elements/react-native-elements/issues/2174).
=> docs(ListItem): Add TouchableHighlight props message (#2174)

README.md, website/core/Footer.js, website/pages/en/help.js
=> docs: Update slack join link

docs/input.md
=> Add password input example

docs/icon.md
Need to regenerate docs. Ref #2288
=> [docs] simple-line-icon correct website link

.github/CONTRIBUTING.MD
Typo correction on the contributing.md
=> Typo correction

src/social/SocialIcon.js, src/social/__tests__/__snapshots__/SocialIcon.js.snap
Fixed #2245  color style of official facebook icon
=> Changing color of Facebook icon

src/input/Input.js, src/input/__tests__/__snapshots__/Input.js.snap, src/searchbar/__tests__/__snapshots__/SearchBar.js.snap
Fixes issue mentioned in #1962
=> fix: Change default left icon styles for input component

src/avatar/__tests__/__snapshots__/Avatar.js.snap, src/image/Image.js, src/image/__tests__/Image.js, src/image/__tests__/__snapshots__/Image.js.snap, src/tile/__tests__/__snapshots__/Tile.js.snap
Applies additional style props provided to `<Image />` to the `<ImageComponent />` and flattens all the styles on this component.
Addresses #2312
=> fix: Image component not applying style prop other than width, height

.github/CONTRIBUTING.MD, docs/contributing.md
=> [Docs]: Minor typographical fix

package.json, yarn.lock
From `v10` modified files are added automatically to the git commit index.
=> chore: update lint-staged config

docs/button_group.md, src/buttons/ButtonGroup.js, src/buttons/__tests__/ButtonGroup.js, src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap, src/index.d.ts
Based on a lot of the code from @k3ithl1m 's PR's towards this goal.
Fixes #869
=> feat: add vertical prop to ButtonGroup

src/tile/FeaturedTile.js, src/tile/Tile.js
Solves https://github.com/react-native-training/react-native-elements/issues/1980
=> Fix tile title font size issue

src/social/__tests__/SocialIcon.js, src/social/__tests__/__snapshots__/SocialIcon.js.snap
=> Haruelrovix test/increase coverage for socialicon

src/buttons/Button.js, src/buttons/__tests__/__snapshots__/Button.js.snap, src/checkbox/CheckBox.js, src/checkbox/__tests__/__snapshots__/CheckBox.js.snap, src/pricing/__tests__/__snapshots__/PricingCard.js.snap
Been deprecated in 0.62 so removing it here as to remove jest errors.
https://github.com/facebook/react-native/pull/26168
=> feat: Remove deprecated accessibilityStates

.github/CONTRIBUTING.MD, docs/contributing.md
=> update contributing docs

src/input/Input.js
=> add useNativeDriver arg to animated input

docs/icon.md, src/helpers/getIconType.js
Update for Fontisto and Documentation change
=> Add Support for Fontisto Font

package.json, src/buttons/__tests__/__snapshots__/Button.js.snap, src/buttons/__tests__/__snapshots__/ButtonGroup.js.snap, src/overlay/__tests__/__snapshots__/Overlay.js.snap, src/pricing/__tests__/__snapshots__/PricingCard.js.snap, src/tile/__tests__/__snapshots__/FeaturedTile.js.snap, src/tile/__tests__/__snapshots__/Tile.js.snap, src/tooltip/__tests__/__snapshots__/Tooltip.js.snap, yarn.lock
=> update test react-native version to 60.6

src/index.d.ts
Add missing `themeKey` to `withTheme` H.O.C.
=> Add themeKey to withTheme

src/avatar/Avatar.js, src/buttons/ButtonGroup.js, src/card/Card.js, src/header/Header.js, src/helpers/index.js, src/helpers/types.js, src/image/Image.js, src/input/Input.js, src/list/ListItem.js, src/searchbar/SearchBar-android.js, src/searchbar/SearchBar-default.js, src/searchbar/SearchBar-ios.js, src/social/SocialIcon.js, src/tile/FeaturedTile.js, src/tile/Tile.js
=> Update Image source props

docs/badge.md, package.json, src/badge/Badge.js, src/badge/__tests__/Badge.js, yarn.lock
=> add textProps prop to Badge

src/checkbox/CheckBox.js, src/checkbox/__tests__/__snapshots__/CheckBox.js.snap
fixes: #2376
This was caused by an attempted fix with: #2331
=> fix checkbox no title spacing issue

src/helpers/getIconStyle.js, src/icons/Icon.js, src/icons/__tests__/__snapshots__/Icon.js.snap, src/pricing/__tests__/__snapshots__/PricingCard.js.snap, src/searchbar/__tests__/__snapshots__/SearchBar.js.snap, src/social/__tests__/__snapshots__/SocialIcon.js.snap
=> only apply styles to icons that can accept them

src/buttons/Button.js, src/buttons/__tests__/__snapshots__/Button.js.snap
=> fix ios raised button issue

src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
=> Add testID to ListItem::PadView

src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
Reverts react-native-elements/react-native-elements#2401
=> Revert "Add testID to ListItem::PadView"

src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
=> fix padview testid placement

docs/image.md, src/image/Image.js, src/image/__tests__/Image.js, src/tile/__tests__/__snapshots__/Tile.js.snap
=> Image methods

docs/button_group.md, src/buttons/ButtonGroup.js, src/index.d.ts
=> Jose4gg feature/add button container style to buttongroup

src/config/fonts.js, src/text/Text.js
fixes: #2191 
@bearbytes
@oxyii 
@seankovacs
I was not able to reproduce directly the issue you were talking about, but can one of you confirm if this fixes the issue?
=> add regular font to all android fonts

docs/tooltip.md, src/index.d.ts, src/tooltip/Tooltip.js, src/tooltip/__tests__/Tooltip.js, src/tooltip/__tests__/__snapshots__/Tooltip.js.snap
=> add toggleAction to tooltip

package.json, src/header/Header.js, src/header/__tests__/__snapshots__/Header.js.snap, yarn.lock
=> Status bar

src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
=> fix padding in list item for web

src/slider/Slider.js, src/slider/__tests__/__snapshots__/Slider.js.snap
=> fix slide web 'not a function' issue

src/avatar/Avatar.js
Fix issue with avatar not displaying if passing containerStyle within imageProps
=> Fix issue with avatar not displaying with imageProps containerStyle

src/avatar/Accessory.js, src/avatar/Avatar.js, src/avatar/__tests__/Accessory.js, src/avatar/__tests__/__snapshots__/Accessory.js.snap, src/avatar/__tests__/__snapshots__/Avatar.js.snap, src/index.d.ts, src/index.js, website/docs/avatar.md, website/docs/getting_started.md, website/versioned_docs/version-0.19.1/getting_started.md, website/versioned_docs/version-1.0.0/getting_started.md, website/versioned_docs/version-1.1.0/getting_started.md, website/versioned_docs/version-1.2.0/getting_started.md, website/versioned_docs/version-2.0.4/getting_started.md
This moves `Accessory` out of `Avatar` into its own component. Still backwards compatible.
=> Avatar rework

src/index.d.ts
=> add type for badge - textProps

src/index.d.ts, src/slider/Slider.js, src/slider/__tests__/__snapshots__/Slider.js.snap, website/docs/slider.md
=> add thumbProps for custom thumb

src/index.d.ts, src/slider/Slider.js, src/slider/__tests__/Slider.js, src/slider/__tests__/__snapshots__/Slider.js.snap, website/docs/slider.md
=> Refactor slider

src/helpers/renderNode.js, src/icons/Icon.js, src/index.d.ts, website/docs/icon.md
=> add iconProps to icon

src/index.d.ts
=> Fix searchbar type to inherit from InputProps

src/bottomSheet/__tests__/__snapshots__/BottomSheet.js.snap, src/list/ListItem.js, src/list/__tests__/__snapshots__/ListItem.js.snap
=> fix issue with listItem alignItems center

README.md
Unified badge styles in README
=> Unifiy badge styles in README

src/bottomSheet/BottomSheet.js, src/bottomSheet/__tests__/BottomSheet.js, src/bottomSheet/__tests__/__snapshots__/BottomSheet.js.snap, src/index.d.ts
Fixes: #2505
* Removed Button component as it is tightly coupled
to BottomSheet Component
* Exposed isVisible prop so that user can easily
manage BottomSheet Component visibililty
=> Fix: Functionality to close the BottomSheet

package.json, src/config/withTheme.js, yarn.lock
=> withTheme fix deepmerge for circular props

src/input/Input.js
=> fix input so that placeholderTextColor is overwritable

src/avatar/Accessory.js, src/avatar/__tests__/__snapshots__/Accessory.js.snap, src/avatar/__tests__/__snapshots__/Avatar.js.snap, src/bottomSheet/__tests__/__snapshots__/BottomSheet.js.snap, src/card/CardDivider.js, src/card/CardFeaturedSubtitle.js, src/card/CardFeaturedTitle.js, src/card/CardImage.js, src/card/CardTitle.js, src/card/__tests__/__snapshots__/Card.js.snap, src/list/ListItemButtonGroup.js, src/list/ListItemCheckBox.js, src/list/ListItemChevron.js, src/list/ListItemContent.js, src/list/ListItemInput.js, src/list/ListItemSubtitle.js, src/list/ListItemTitle.js, src/list/__tests__/__snapshots__/ListItem.js.snap, website/docs/customization.md
Add theming to new subcomponents.
=> add theming to subcomponents

yarn.lock
=> update types to RN 63

src/index.d.ts
Fixes: #2523
@ottob @SimenB please check this out and double check my work here before I submit it.
=> fix new subcomponent types

src/index.d.ts
Fixes: #2522 and #2492
@djMax please check this out and see if this fixes the issue.
@SrBrahma @hengkx please also check this out for the fix on the other ticket as well.
=> fix touchable type

src/index.d.ts
=> fix children in typescript

src/input/Input.js
=> Fix input style

src/config/ThemeProvider.js, src/config/__tests__/ThemeProvider.js
=> fix: ThemeProvider re-render on prop change

README.md
Preview -> https://github.com/pranshuchittora/react-native-elements/blob/docs/readme/README.md
=> docs: Added GitHub stars img shield

src/buttons/Button.js
=> fix: Ripple overflow on Button with borderRadius

src/searchbar/SearchBar-android.js
=> fix(SearchBar-Android): Fires onCancel when back button is pressed while typing

.npmignore, package.json
=> feat(tooling): Reduced package size by removing unwanted files in the tar.

src/config/__tests__/colors.js, src/config/index.js
=> feat(Colors): Dark colors are now available in the Public API

src/avatar/__tests__/__snapshots__/Avatar.js.snap, src/image/Image.js, src/image/__tests__/__snapshots__/Image.js.snap, src/index.d.ts, src/tile/__tests__/__snapshots__/Tile.js.snap, website/docs/image.md
=> feat(Image): Perf improvements and transitionDuration

src/slider/Slider.js
Issues Fixed.
- allowTouchTrack` Slider thump position is off when sliding #2509
- Slider stuck when value is set #2515
Closes #2515 
Closes #2509
=> fix(Slider): Slider stuck when value is set initially and slider stuck issue.

src/buttons/Button.js, src/buttons/__tests__/__snapshots__/Button.js.snap, src/pricing/__tests__/__snapshots__/PricingCard.js.snap
=> fix(Button): Improper text alignment

src/image/__tests__/__snapshots__/Image.js.snap
=> chore(tests): Snapshot updates

website/docusaurus.config.js
=> move url to reactnativeelements.com

website/docs/checkbox.md
Rearranged the props section and reference section of documentation of checkbox in an alphabetical order.
Fix for #2604
=> Docs (checkbox.md): Arrange props and references alphabetically

website/docs/overlay.md
ModalComponent was not in order. I've rearranged it.
=> Sorted components in alphabetical order in modal.md file.

website/docs/badge.md, website/docs/button.md
This arranges the props lists in badge.md and button.md to be alphabetical.
=> Docs: arrange props alphabetically in badge.md, button.md

website/docusaurus.config.js, website/versioned_docs/version-1.2.0/getting_started.md, website/versioned_docs/version-2.0.4/getting_started.md, website/versioned_docs/version-2.2.1/getting_started.md, website/versioned_docs/version-2.3.2/getting_started.md
=> Replace homePageId with slug

website/versioned_docs/version-1.2.0/tooltip.md, website/versioned_docs/version-2.0.4/tooltip.md, website/versioned_docs/version-2.2.1/tooltip.md
#2613 - I found broken URL for the image in Tooltip docs
=> Update broken URLs

website/docs/listitem.md, website/docs/searchbar.md
Fixed the prop list for an easy understanding of the docs.
=> Docs: arrange props alphabetically in searchbar.md, listitem.md 

package.json, yarn.lock
=> update status-bar-height lib

src/index.d.ts
=> checkbox type

website/docs/customization.md, website/docs/listitem.md, website/versioned_docs/version-1.2.0/customization.md, website/versioned_docs/version-1.2.0/listitem.md, website/versioned_docs/version-2.0.4/customization.md, website/versioned_docs/version-2.0.4/listitem.md, website/versioned_docs/version-2.2.1/customization.md, website/versioned_docs/version-2.2.1/listitem.md, website/versioned_docs/version-2.3.2/customization.md, website/versioned_docs/version-2.3.2/listitem.md
Fixes a few typos in the documentation
=> Typo fixes on Customization and ListItem page

src/index.d.ts
=> fix Tile type file

website/src/pages/index.js
Fixes:  #2602 Add an image to the website homepage and make it look a nicer.
=> add image to website homepage

website/docs/avatar.md, website/versioned_docs/version-2.3.2/avatar.md
=> removing deprecated Avatar section of docs

src/buttons/Button.js
Button onPress should pass down the evt object.
=> Button onPress should pass down the evt object.

src/image/Image.js, src/tile/__tests__/__snapshots__/Tile.js.snap
Fixes:  #2714
@Aparus please check out this change and see if that fixes it.
=> fix image source for local images

src/header/Header.js, src/header/__tests__/__snapshots__/Header.js.snap
Fixes: #2713 
@Aparus please check this out and see if that fixes your issue.
=> fix Header placement on web

website/docs/button_group.md, website/docs/text.md
=> alphabetize ButtonGroup and Text props

src/bottomSheet/BottomSheet.js, src/bottomSheet/__tests__/BottomSheet.js, src/bottomSheet/__tests__/__snapshots__/BottomSheet.js.snap
Fixes: #2726
@guilhermedess can you try this out and see if everything works as expected?
=> update BottomSheet so that it isn't bound by a max height

src/buttons/Button.js, src/index.d.ts, website/docs/button.md
=> Button title use renderNode

website/docs/bottomsheet.md, website/docs/getting_started.md, website/docs/header.md, website/versioned_docs/version-3.1.0/bottomsheet.md, website/versioned_docs/version-3.1.0/getting_started.md, website/versioned_docs/version-3.1.0/header.md
=> add note for rn-safe-area-context setup

.github/CONTRIBUTING.MD, README.md
=> update app location

src/badge/Badge.tsx, src/buttons/ButtonGroup.tsx, src/card/Card.tsx, src/card/CardDivider.tsx, src/card/CardFeaturedSubtitle.tsx, src/card/CardFeaturedTitle.tsx, src/card/CardImage.tsx, src/card/CardTitle.tsx, src/checkbox/CheckBox.tsx, src/divider/Divider.tsx, src/header/Header.tsx, src/helpers/index.tsx, src/image/Image.tsx, src/input/Input.tsx, src/list/ListItem.tsx, src/list/ListItemButtonGroup.tsx, src/list/ListItemCheckBox.tsx, src/list/ListItemContent.tsx, src/list/ListItemInput.tsx, src/list/ListItemSubtitle.tsx, src/list/ListItemTitle.tsx, src/pricing/PricingCard.tsx, src/searchbar/SearchBar-android.tsx, src/searchbar/SearchBar-default.tsx, src/searchbar/SearchBar-ios.tsx, src/text/Text.tsx, src/tooltip/Tooltip.tsx
=> typescript migration

website/docs/props/rating.md
Update the documentation to include TintColor for the Rating component
=> Updated the docs for the Rating component issue #2780

.github/ISSUE_TEMPLATE/feature-request.md
Update `feature-request.md`.
Mark question description as a comment,  as they are for the author's eye only.
=> chore: update feature request template

website/src/pages/help.js
Fixes:  #2827 
Corrected links 
not needed 
not needed 
**Summary**
this pr corrects the post an issue and existing issue link 
This Pr corrects the link of post an issue and existing issue 
=> docs: corrected post an issue and existing issue link

website/src/pages/index.js, website/src/pages/versions.js, website/static/css/components.css
feature and bugfix
No
**Summary**
Array nullability was a possible issue
UI fixes were made
No
for the UI change on mobile components
Before my change
after my change 
the result
=> docs: UI fixes and array nullability check

src/buttons/Button.tsx, src/buttons/ButtonGroup.tsx, src/buttons/__tests__/Button.js, src/checkbox/CheckBox.tsx, src/pricing/PricingCard.tsx, src/pricing/__tests__/__snapshots__/PricingCard.js.snap
bugfix: removed ts-ignore and changed to functional component
I changed 
Fixing #2798 
**Summary**
=> Removed ts-ignore and transformed to Functional Component

src/icons/Icon.tsx, src/social/SocialIcon.tsx, yarn.lock
=> fix vector icons types package version difference

src/avatar/Avatar.tsx, src/card/CardFeaturedSubtitle.tsx, src/card/CardFeaturedTitle.tsx, src/card/CardTitle.tsx, src/config/withTheme.tsx, src/header/Header.tsx, src/social/SocialIcon.tsx, src/tile/FeaturedTile.tsx, src/tile/Tile.tsx
In this I fixed ts-ignore errors in
**Summary**
Removed ts-ignore in few components
=> Removed ts-ignore

src/config/index.tsx, src/index.ts
FullTheme type missing
**Summary**
Fixing #2858 
=> Added FullTheme

website/src/pages/index.js
bug fix
No
No
**Summary**
Read docs and playground button doesn't look good when we hover over it. Now, I fix #2863 that it'll improve the user experience.
No
=> fix read docs and playground button

.github/CONTRIBUTING.MD, website/docs/contributing.md, website/docs/getting_started.md, website/docs/troubleshooting.md
docs
no
yes
**Summary**
`rpm install` gives error sometimes leading to confusion to new contributors, encourage contributors to use `yarn`
no
no
=> docs: remove npm reference in contributing.md

src/config/index.tsx, src/config/theme.tsx, src/index.ts
=> add Theme exports

src/badge/Badge.tsx, src/buttons/Button.tsx, src/buttons/ButtonGroup.tsx, src/card/Card.tsx, src/checkbox/CheckBoxIcon.tsx, src/config/index.tsx, src/divider/Divider.tsx, src/header/Header.tsx, src/icons/Icon.tsx, src/image/Image.tsx, src/index.ts, src/input/Input.tsx, src/list/ListItem.tsx, src/pricing/PricingCard.tsx, src/searchbar/SearchBar.tsx, src/text/Text.tsx, src/tooltip/Tooltip.tsx
Fixed ts-ignore issue resulted from theme prop
=> Removed ts-ignore from various components

src/searchbar/SearchBar.tsx
i guess one more left for searchBar //@ts-ignore error
=> remove ts-ignore error

.ci/setupTests.js, src/searchbar/SearchBar-ios.tsx, tsconfig.json
=> Remove remaining ts-ignore's

src/slider/Slider.tsx
I added a listener for the getting current value, earlier it was using `__getValue()` method, but wasn't in TS
=> Strict Typescript Slider

website/docs/props/tab.md
fixes #2966 
Added Missing indicatorStyle Prop to tab.md
@flyingcircle please review
=> Adding Missing Prop indicatorStyle in tab.md fixes #2966

src/buttons/Button.tsx, src/buttons/FAB.tsx, src/buttons/SpeedDial.tsx, src/buttons/__tests__/__snapshots__/SpeedDial.js.snap, src/config/index.tsx, src/config/theme.tsx, src/linearProgress/index.ts, src/list/ListItemAccordion.tsx, src/tab/tab.tsx
=> Fixing issues

website/versioned_docs/version-3.3.2/avatar.md
Line no: 166 documentation correction    <ListItem.SubTitle>{role}</ListItem.Subtitle> ​
to <ListItem.SubTitle>{role}</ListItem.SubTitle>
**Summary**
=> Documentation correction avatar.md

src/list/ListItem.tsx
Changed PadView component in ListItem.tsx from class based to function based component, using necessary hooks and types.
=> changed padView class component  to functional component

src/buttons/Button.tsx, src/pricing/__tests__/__snapshots__/PricingCard.js.snap, website/docs/props/button.md
=> Replaced iconRight with iconPosition

src/buttons/SpeedDial.tsx, src/buttons/__tests__/__snapshots__/SpeedDial.js.snap, website/docs/props/fab.md
=> Fixed SpeedDial

src/divider/Divider.tsx, website/docs/props/divider.md
=> Fix Divider style props

package.json, src/config/theme.tsx, src/index.ts, yarn.lock
=> Chore: Upgrade react-native-ratings dependency

website/docs/speeddial.md
=> [docs] Fixed SpeedDial Demo Code

src/tab/tab.tsx
=> [Tab] Fixed Tab

website/docs/props/button.md
This change adds a link for the `iconPosition` prop in the button props doc.
=> adds link to iconPosition prop in the button props doc

src/helpers/getIconStyle.tsx, src/helpers/getIconType.tsx, src/icons/Icon.tsx, website/docs/icon.md, website/docs/props/icon.md
Icon component changes:
- Added support for the "font-awesome-5-pro" value for the **type** prop.
- Added **light** prop.
Updated the list of available icon sets.
Added a description of the **light**.
No.
=> Support for Font Awesome 5 Pro

src/helpers/getIconStyle.tsx, src/helpers/getIconType.tsx, src/icons/Icon.tsx, website/docs/icon.md, website/docs/props/icon.md
Reverts react-native-elements/react-native-elements#2962
=> Revert "Support for Font Awesome 5 Pro"

src/input/Input.tsx, src/input/__tests__/__snapshots__/Input.tsx.snap, src/searchbar/__tests__/__snapshots__/SearchBar.tsx.snap, src/social/SocialIcon.tsx
- The label was only of type React.ReactNode but it should be string | React.ReactNode
- Added more valid types to the props.
- Fix Social icon activityIndicatorStyle prop
=> [Fix] Input and SocialIcon props

src/icons/Icon.tsx, website/docs/header.md
=> [fix] Header subcomponents iconStyle prop

.ci/setupTests.ts, package.json, website/package.json, website/src/pages/help.tsx, website/src/pages/index.tsx, website/src/pages/versions.tsx, website/tsconfig.json, website/yarn.lock
Converts the existing Document website code to typescript. This PR also adds a script which enables running docs from project directory.
Not required
Yes
**Summary**
As mentioned above
No
Not required
=> [Refactor] Convert Docusaurus code to typescript and added script

website/versioned_docs/version-3.4.2/tab.md
=> [docs] Tab demo code 

src/list/ListItemSwipeable.tsx, website/docs/props/listitem.md
=> [ListItem] Swipable add onLeftSwipe & onRightSwipe props

.github/workflows/build-and-deploy-to-dist.yml
=> [docs] Added CNAME 

src/SearchBar/SearchBar.tsx
=> [SearchBar] Fixes broken types #3089

website/package.json, website/yarn.lock
=> [website] Missing Packages

website/src/components/Features.tsx
Fixed typos in the Homepage on lines 14 and 52 of Features.tsx
Fix grammar mistakes presented in the homepage, specifically the Features.tsx component.
No.
No.
=> Fix typos/grammar mistakes in Features.tsx

tsconfig.json
This PR fixes the compilation issues with the package.
Disclaimer: This main cause docgen scripts to not run. I will look into that fix and raise a PR for that issue soon.
=> [Fix] Compilation issues

src/LinearProgress/LinearProgress.tsx, src/LinearProgress/index.tsx
- Added new prop for stop animation and change duration, 
- If `value` is provided no need to describe `variant='deteminate'`
No
Not required
**Summary**
Closes #3156
=> [LinearProgress] Prop for animations 

website/src/components/OpenCollective.tsx, website/src/pages/versions.tsx
Minor bugfix
No, this change should not require additional or updated tests.
N/A
**Summary**
Links that contain `target="_blank"` as a best practice should also include the `rel` property with `noopener` and `noreferrer` to prevent tabnabbing. Since these are links to pages that are owned by the maintainers of this repo this change isn't super important, however.
N/A
N/A
=> Add noopener and noreferrer to links opening a new tab

.github/ISSUE_TEMPLATE/pr-deploy.yml
Using https://github.com/expo/expo-github-action
Source https://github.com/callstack/react-native-paper/blob/main/.github/workflows/publish-each-pr.yml
=> Add expo CI

src/LinearProgress/LinearProgress.tsx, src/LinearProgress/__tests__/LinearProgress.test.tsx, src/LinearProgress/__tests__/__snapshots__/LinearProgress.test.tsx.snap
=> Fix LinearProgress Clamp

.github/workflows/docs.yml
=> Fix cache in docs CI

src/Avatar/Avatar.tsx, src/Badge/Badge.tsx, src/Icon/Icon.tsx, src/Image/Image.tsx, src/LinearProgress/LinearProgress.tsx, src/LinearProgress/__tests__/LinearProgress.test.tsx, src/SocialIcon/SocialIcon.tsx, website/docs/main/AirbnbRating.md, website/docs/main/Avatar.md, website/docs/main/Badge.md, website/docs/main/Header.md, website/docs/main/Icon.md, website/docs/main/Image.md, website/docs/main/SocialIcon.md, website/docs/main/Text.md, website/scripts/docgen/docgenParser.ts
This uses `@default` tag of TSDoc
=> Update autoDocgen Default Value

.github/workflows/expo.yml
Publish PR to expo and comment QR code
This might be helpful in quick review of PRs, c.c. @flyingcircle
=> Add expo publish preview workflow

.github/workflows/dist.yml, .gitignore, README.md, package.json, packages/base/.gitignore, tsconfig.json, website/docs/getting_started.md
=> Add actions for deploy bleeding edge version

example/src/views/circularSlider.tsx, example/tsconfig.json, packages/base/README.md, packages/universe/.gitignore, packages/universe/.prettierrc, packages/universe/.travis.yml, packages/universe/README.md, packages/universe/babel.config.js, packages/universe/package.json, packages/universe/src/CircularSlider/CircularSlider.tsx, packages/universe/src/CircularSlider/__tests__/CircularSlider.test.tsx, packages/universe/src/CircularSlider/index.ts, packages/universe/src/index.ts, packages/universe/tsconfig.json, tsconfig.json, yarn.lock
=> Add `@react-native-elements/universe` package

website/docs/main/Input.mdx, website/versioned_docs/version-4.0.0-beta.0/main/Input.md
Bugfix 
No
No
**Summary**
Updates broken link to React Native docs. 
No 
=> Updates broken link to React Native TextInput docs

.github/FUNDING.yml, .github/workflows/docs.yml, .github/workflows/test.yml, .husky/pre-commit, .prettierignore, README.md, example/package.json, package.json, packages/base/.ci/setupTests.ts, packages/base/.ci/testHelper.tsx, packages/base/README.md, packages/base/package.json, packages/themed/.ci/setupTests.ts, packages/themed/.ci/testHelper.tsx, packages/themed/README.md, packages/themed/package.json, packages/universe/README.md, packages/universe/package.json, tsconfig.json, website/docs/main/TabView.mdx, website/docs/web_usage.md, website/package.json, website/yarn.lock, yarn.lock
=> refactor: packages

website/docs/main/usage/Icon/Icon.mdx, website/versioned_docs/version-4.0.0-beta.0/main/usage/Icon/Icon.md
It updates the documentation of Icon component.
No tests were added.
Yes.
**Summary**
**Fixes issue #3197**
The icon documentation had no link to a page which displayed all the supported icons.
This PR solves it by adding a link to the required page in the documentation.
No.
=> Fix: Issue #3197 Update Icon documentation

website/versioned_docs/version-4.0.0-beta.0/customization.md
It changes the documentation of customization. 
No .
Yes
**Summary**
Fixes issue #3309 
Documentation had errors in code. These were fixed.
No 
=> Fix: Issue #3309 Customization Documentation

packages/base/src/ListItem/ListItem.Accordion.tsx
Added testID to listItem.Accordion views.
Added generic TestIDs as all testIDs in other components were also generic. 
No, my changes do not affect the code.
No.
**Summary**
These changes were made in response to this issue : https://github.com/react-native-elements/react-native-elements/issues/3256
No.
**Other info**
I'm new to react-native, please review and tell me if this change is what was required to fix the above mentioned issue. Thanks.
=> test(ListItem): add testID in Accordion

website/versioned_docs/version-4.0.0-beta.0/getting_started.md
one word missing
yes
**Summary**
=> docs: update installation page

website/docs/components/usage/SearchBar/snack/index.md, website/versioned_docs/version-4.0.0-beta.0/main/usage/SearchBar/snack/index.md
Hi dear,
I have fixed the issue as the code seems a mixture of the class-based and functional components.
This just help to copy and paste the correct working codes based on functional component. Also, snack is now working perfectly.
Yes, I have tested.
**Summary**
I am seeing this issue a long time it is not just working in live snack.
Yes, it breaks the snack output.
=> docs: Update Seachbar Snack Codes

example/src/navigation/RootNavigator.tsx, example/src/views/theme.tsx
=> example: add Theme View

example/src/views/lists2.tsx
=> example: update ListItem.Swipeable view
